const SLIDESHOW_IDEAS = [
  {
    id:"s1",title:"\"I Fw This\" → Broke → Offer → CTA",potential:98,difficulty:1,tags:["conversion","PAS","proven"],platforms:["TikTok Spark Ad"],duration:"4 slides",
    hook:"Outfit collage + 'I fw this heavy'",
    hookNote:"YOUR OWN PROVEN FORMAT. Outfit collage shows the vibe → empty wallet = relatable problem → product + offer = solution → logo + CTA = close. Problem-Agitate-Solve in 4 slides. Direct conversion flow.",
    textOverlay:"Slide 1: 'I fw this heavy 🔥' — Slide 2: 'but my bank account:' — Slide 3: 'NEWGARMENTS — Premium 460 GSM Hoodie — €45' — Slide 4: 'Click Shop Now to upgrade your style without overpaying'",
    cta:"Shop Now button via Spark Ad",
    why:"PAS framework is the #1 proven conversion structure in direct response. The 'broke' slide makes it relatable (everyone knows this feeling), the offer slide solves it (€45 = affordable). The collage shows multiple outfits in 1 slide = more value per swipe.",
    psychology:"'I fw this' = social validation (others think this is fire). Empty wallet = shared problem that lowers resistance. €45 price point = the solution. CTA = direct action. Entire flow in 4 slides = high completion rate.",
    proof:[{brand:"NEWGARMENTS own post",detail:"Proven format on @newgarmentsclo. Outfit collage + problem/solution flow."},{brand:"PAS framework",detail:"Problem-Agitate-Solve = #1 conversion framework in direct response advertising."},{brand:"Price anchoring",detail:"€45 after 'broke' context = feels like a solution, not an expense."}],
    equipment:["4+ outfit photos for collage (slide 1)","Photo of empty wallet or bank app showing €0","Product photos for collage (slide 3)","NEWGARMENTS logo (slide 4)"],
    caption:"the one 🤞",
    audio:"Trending lo-fi or soft beat",
    firstSlide:"Collage of 4 outfit photos with NEWGARMENTS hoodie styled. Text: 'I fw this heavy 🔥'",
    backedBy:"Own proven post, PAS conversion framework, price anchoring psychology",
    sourceLinks:[{label:"NEWGARMENTS Own Post (this format)",url:"https://www.tiktok.com/@newgarmentsclo/photo/7590800763165723937"}],
    goal:"CONVERSION. Direct to shop. Entire flow is built to sell.",
    imageRules:"Slide 1 = collage layout (4 outfit photos in grid). Slide 2 = single image (empty wallet). Slide 3 = product collage with price. Slide 4 = logo centered on dark background with CTA text.",
    steps:[
      {title:"Slide 1: The Hook — Outfit Collage",action:"Create a collage of 4 outfit photos wearing the NEWGARMENTS hoodie in different styles. Grid layout (2x2). Text overlay: 'I fw this heavy 🔥'. The collage must look FIRE — your best looks.",camera:"Phone — 4 separate outfit photos, combine in Canva/CapCut",angle:"Mix of full body, mirror selfie, candid, friend-shot",lighting:"Natural, consistent per photo",duration:"10 min",tip:"The collage IS the hook. If it doesn't look hard, nobody swipes. Use your 4 strongest outfit photos."},
      {title:"Slide 2: The Problem — Broke",action:"Photo of an EMPTY wallet, or screenshot of bank app showing €0.00, or hands showing empty pockets. Text overlay: 'but my bank account:' — This is the relatable moment. EVERYONE knows this feeling.",camera:"Phone — close-up",angle:"Close-up of empty wallet or bank app",lighting:"Doesn't matter — it's about the message",duration:"2 min",tip:"The worse the 'broke' slide looks, the better the contrast with slide 3."},
      {title:"Slide 3: The Solution — Product + Offer",action:"Collage of NEWGARMENTS products with prices. Text: 'NEWGARMENTS — Premium 460 GSM Hoodie — €45'. Show multiple colorways. This is where you SELL. Price must be VISIBLE.",camera:"Product photos — clean shots of hoodies",angle:"Flat lay or product shots, collage layout",lighting:"Clean, well-lit",duration:"10 min",tip:"The price (€45) is crucial. After the 'broke' slide, €45 feels like a solution, not an expense."},
      {title:"Slide 4: CTA — Logo + Action",action:"NEWGARMENTS logo centered on dark background. Text: 'Click Shop Now to upgrade your style without overpaying'. This is the CLOSE — clear call to action.",camera:"Canva/design — logo + text",angle:"N/A — graphic",lighting:"N/A",duration:"5 min",tip:"The CTA must be CLEAR. No ambiguity. 'Shop Now' + why (without overpaying)."}
    ]
  },
  {
    id:"s2",title:"\"POV: Finding The Perfect Hoodie\" Search",potential:96,difficulty:1,tags:["conversion","POV","relatable"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Screenshots of overpriced hoodies + 'POV: looking for the perfect hoodie'",
    hookNote:"POV format — everyone knows the frustration of searching for quality at a fair price. You show the PROBLEM (too expensive, too cheap), then THE SOLUTION (your hoodie). Conversion flow: problem → frustration → discovery → proof → CTA.",
    textOverlay:"Slide 1: 'POV: looking for the perfect hoodie' — Slide 2: 'but everything is trash or overpriced 💀' — Slide 3: 'until you find this' — Slide 4: '460 GSM — thicker than you think' — Slide 5: '€45 — Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"POV = most native TikTok format. The search is universally relatable. You position NEWGARMENTS as a discovery they 'find themselves', not an ad being pushed on them. Discovery framing = lower ad resistance.",
    psychology:"The viewer recognizes the search (everyone's been through this). Frustration builds tension. The 'discovery' feels like THEIR win, not your pitch. €45 after screenshots of €90+ = instant price anchoring.",
    proof:[{brand:"POV format",detail:"POV = #1 TikTok storytelling format. Billions of views."},{brand:"Price anchoring",detail:"By showing €90+ first, €45 feels like a steal."},{brand:"Discovery framing",detail:"Product as 'discovery' = 40% lower ad resistance than direct pitch."}],
    equipment:["Screenshots of expensive hoodies (€80-120) from other sites","Screenshots of cheap hoodies (bad quality, bad reviews)","NEWGARMENTS hoodie on-body photo","Close-up fabric detail photo","Logo + price graphic"],
    caption:"finally 🤝",
    audio:"Trending discovery/reveal sound",
    firstSlide:"Screenshots of overpriced hoodies (€80-120) with text 'POV: looking for the perfect hoodie'",
    backedBy:"POV format (billions of views), price anchoring psychology, discovery framing",
    sourceLinks:[{label:"POV Fashion Shopping TikTok",url:"https://www.tiktok.com/discover/pov-looking-for-the-perfect-hoodie"},{label:"Hoodie Hunt TikTok",url:"https://www.tiktok.com/discover/best-hoodie-under-50"}],
    goal:"CONVERSION. Price anchoring + discovery framing → Shop Now.",
    imageRules:"Slide 1-2 = screenshots of OTHER brands (make the problem visual). Slide 3 = your product on-body (the switch). Slide 4 = close-up detail (proof). Slide 5 = logo + price + CTA.",
    steps:[
      {title:"Slide 1: The Problem — Too Expensive",action:"Screenshots of expensive hoodies from known brands. Prices clearly visible (€80, €95, €120). Text overlay: 'POV: looking for the perfect hoodie'. Show MULTIPLE screenshots in a collage.",camera:"Screenshots from webshops",angle:"Screen recording or screenshot collage",lighting:"N/A",duration:"5 min",tip:"Use real prices from known brands. The sticker shock IS the hook."},
      {title:"Slide 2: The Frustration — Bad Quality",action:"Screenshots of cheap hoodies: bad reviews, pilling photos, thin fabric. Text: 'but everything is trash or overpriced 💀'. This builds the frustration — too expensive OR bad quality.",camera:"Screenshots of reviews/complaints",angle:"Collage of 'fails'",lighting:"N/A",duration:"5 min",tip:"Real 1-star reviews from fast fashion hoodies. 'Fell apart after 2 washes' etc."},
      {title:"Slide 3: The Discovery — Your Product",action:"SWITCH to NEWGARMENTS hoodie on person. Beautiful shot, native feel. Text: 'until you find this'. This is the turning point — from problem to solution.",camera:"Phone — friend-shot or mirror selfie",angle:"Full outfit, best angle",lighting:"Natural, warm",duration:"",tip:"The contrast with slides 1-2 must be HUGE. From screenshots to a real, beautiful photo."},
      {title:"Slide 4: The Proof — Detail",action:"Close-up of the fabric. The THICKNESS of 460 GSM is visual. Label, stitching, texture. Text: '460 GSM — thicker than you think'. Show the quality, don't just say it.",camera:"Phone — macro/close-up",angle:"Close-up fabric, label, stitching",lighting:"Good light so texture is visible",duration:"",tip:"The thickness of 460 GSM is your USP. When people SEE it, they want to FEEL it."},
      {title:"Slide 5: CTA — Price + Action",action:"NEWGARMENTS logo + '€45' large + 'Shop Now ⬇️'. Dark background with bright text. The price after slide 1 (€80-120) feels like a no-brainer.",camera:"Canva/design",angle:"N/A — graphic",lighting:"N/A",duration:"5 min",tip:"€45 after the €90+ screenshots = instant price anchoring. The deal is obvious."}
    ]
  },
  {
    id:"s3",title:"\"What €45 Gets You\" Price Anchor",potential:97,difficulty:1,tags:["conversion","comparison","price-anchor"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Competitor hoodie + 'What €90 gets you'",
    hookNote:"Direct price comparison. You show FIRST what an expensive hoodie gives you, then what NEWGARMENTS gives you for half the price. Price anchoring = most powerful conversion trigger. The viewer does the math themselves.",
    textOverlay:"Slide 1: 'What €90 gets you:' — Slide 2: '280 GSM, single stitched, basic fit' — Slide 3: 'What €45 gets you at NEWGARMENTS:' — Slide 4: '460 GSM, double stitched, boxy oversized fit' — Slide 5: '€45 — Shop Now'",
    cta:"Shop Now via Spark Ad",
    why:"Price anchoring is the #1 conversion trigger in advertising. By showing €90 first, €45 feels like a steal. The specific specs (460 GSM vs 280 GSM) give an objective reason to buy. This isn't opinion — it's facts.",
    psychology:"Anchoring bias: the first number you see (€90) becomes your reference point. Everything after is compared to €90. €45 = 50% less = instant 'deal' feeling. Specific numbers (460 GSM vs 280 GSM) = credibility.",
    proof:[{brand:"Price anchoring",detail:"#1 conversion trigger. First price sets the reference frame."},{brand:"Comparison format",detail:"Side-by-side comparisons = 20-30% higher CTR on TikTok."},{brand:"Specific specs",detail:"Numbers (460 GSM, €45) = objective proof. More convincing than 'premium quality'."}],
    equipment:["Photos of a 'standard' hoodie (thin, basic)","NEWGARMENTS hoodie photos (on-body + details)","Close-up comparison photos (thickness, stitching)","Logo + price graphic"],
    caption:"you decide 🤷",
    audio:"Trending beat or reveal sound",
    firstSlide:"Split-screen or comparison: expensive hoodie (€90) — text: 'What €90 gets you:'",
    backedBy:"Price anchoring psychology (#1 conversion trigger), comparison format (+20-30% CTR)",
    sourceLinks:[{label:"Price Comparison Fashion TikTok",url:"https://www.tiktok.com/discover/hoodie-price-comparison"},{label:"What Your Money Gets You",url:"https://www.tiktok.com/discover/what-your-money-gets-you-fashion"}],
    goal:"CONVERSION. Price anchoring → viewer does the math → your product is the obvious deal.",
    imageRules:"Slide 1-2 = competitor/generic hoodie (make it look 'meh'). Slide 3-4 = NEWGARMENTS hoodie (make it look premium). The visual contrast must be OBVIOUS. Slide 5 = logo + price + CTA.",
    steps:[
      {title:"Slide 1: The Anchor — Expensive Competitor",action:"Photo of a generic/expensive hoodie. Looks basic. Text: 'What €90 gets you:'. This sets the price reference frame. The viewer thinks: '€90 for THIS?'",camera:"Photo of a basic hoodie (can be your own old one)",angle:"Flat lay or hanger — make it look 'meh'",lighting:"Normal — don't make it look good",duration:"3 min",tip:"It must look BASIC. No styling, no atmosphere. Just a hoodie."},
      {title:"Slide 2: The Specs — What You Get for €90",action:"Close-up of thin fabric, single stitching, basic label. Text: '280 GSM, single stitched, basic fit'. Show the DISAPPOINTMENT — thin fabric, nothing special.",camera:"Phone — close-up of thin fabric",angle:"Detail shots that show 'cheap'",lighting:"Normal",duration:"3 min",tip:"280 GSM vs 460 GSM = the difference is VISIBLE and FEELABLE. Show how thin it is."},
      {title:"Slide 3: The Switch — NEWGARMENTS",action:"NEWGARMENTS hoodie on person. Premium feel, beautiful shot. Text: 'What €45 gets you at NEWGARMENTS:'. The CONTRAST with slides 1-2 must hit hard. From basic to premium.",camera:"Phone — friend-shot",angle:"Full outfit, styled, best angle",lighting:"Warm, natural, beautiful",duration:"",tip:"This is the 'holy shit' moment. From a boring hoodie to YOUR hoodie. Make it look incredible."},
      {title:"Slide 4: The Proof — Specs",action:"Close-up details: thick fabric, double stitching, premium label, boxy fit. Text: '460 GSM, double stitched, boxy oversized fit'. PROVE it's better — don't say it, SHOW it.",camera:"Phone — macro/detail shots",angle:"Close-up fabric thickness, stitching, label",lighting:"Good light on details",duration:"",tip:"Hold the fabric next to a pen or coin for scale. 460 GSM is CLEARLY thicker."},
      {title:"Slide 5: CTA — Price + Action",action:"Logo + '€45' + 'Shop Now ⬇️'. After the €90 anchor, €45 feels like a steal. Dark background, bright text.",camera:"Canva/design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"The math does itself: better product, half the price. CTA is a no-brainer."}
    ]
  },
  {
    id:"s4",title:"\"Stop Buying Fast Fashion\" Quality Proof",potential:95,difficulty:1,tags:["conversion","quality","anti-fast-fashion"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Pilled hoodie + 'Stop buying fast fashion hoodies'",
    hookNote:"Anti-fast-fashion angle. You show the PROBLEM (pilling, fading after 2 washes), then the SOLUTION (460 GSM that lasts). Visual quality proof sells better than marketing claims. The viewer sees the difference with their own eyes.",
    textOverlay:"Slide 1: 'Stop buying fast fashion hoodies' — Slide 2: 'This is what you get after 2 washes 💀' — Slide 3: 'This is 460 GSM after 6 months ✅' — Slide 4: 'Built to last. €45.' — Slide 5: 'NEWGARMENTS — Shop Now'",
    cta:"Shop Now via Spark Ad",
    why:"Anti-fast-fashion sentiment is HUGE with Gen Z. 73% want to buy more sustainably. By making the problem visual (pilling) and showing the solution (460 GSM after 6 months), you give an objective reason to switch.",
    psychology:"Loss aversion: people hate wasting money. When they SEE a €20 hoodie destroyed after 2 washes, they realize they spend MORE by buying cheap. €45 for something that lasts 6+ months = savings.",
    proof:[{brand:"Anti-fast-fashion",detail:"73% of Gen Z wants to buy more sustainably. Anti-fast-fashion content = massive engagement."},{brand:"Before/after quality",detail:"Visual quality proof = 94% higher conversion than claims alone."},{brand:"Loss aversion",detail:"People react stronger to avoiding loss than gaining benefit."}],
    equipment:["Old pilled/faded hoodie (or buy a cheap one)","NEWGARMENTS hoodie worn for 6+ months","Close-up comparison photos","Logo + price graphic"],
    caption:"quality > quantity",
    audio:"Serious/impactful trending sound",
    firstSlide:"Close-up of pilled, faded fast fashion hoodie. Text: 'Stop buying fast fashion hoodies'",
    backedBy:"Anti-fast-fashion Gen Z sentiment (73%), visual quality proof (+94% conversion)",
    sourceLinks:[{label:"Fast Fashion vs Quality TikTok",url:"https://www.tiktok.com/discover/fast-fashion-vs-quality-hoodie"},{label:"Anti Fast Fashion",url:"https://www.tiktok.com/discover/stop-buying-fast-fashion"}],
    goal:"CONVERSION. Quality proof + loss aversion → 'I'm done wasting money' → Shop Now.",
    imageRules:"Slides 1-2 = UGLY close-ups of bad quality (pilling, fading, thin fabric). Slides 3-4 = BEAUTIFUL shots of NEWGARMENTS (still perfect after 6 months). Slide 5 = logo + price + CTA.",
    steps:[
      {title:"Slide 1: The Problem — Fast Fashion",action:"Close-up of a pilled, faded hoodie. Fabric is thin, color faded, pilling everywhere. Text: 'Stop buying fast fashion hoodies'. This stops the scroll with a bold statement.",camera:"Phone — close-up",angle:"Close-up of pilling, fading, bad quality",lighting:"Good light so pilling is CLEARLY visible",duration:"3 min",tip:"Use a real old hoodie. The worse it looks, the stronger the point."},
      {title:"Slide 2: Proof — After 2 Washes",action:"Another close-up of bad quality. Optionally before/after: 'just bought' vs 'after 2 washes'. Text: 'This is what you get after 2 washes 💀'. The skull emoji makes it relatable/funny.",camera:"Phone",angle:"Close-up detail — pilling, holes, fading",lighting:"Bright",duration:"3 min",tip:"If you have a before/after of the same hoodie = even more powerful."},
      {title:"Slide 3: The Solution — 460 GSM After 6 Months",action:"NEWGARMENTS hoodie you've been wearing for MONTHS — still perfect. Text: 'This is 460 GSM after 6 months ✅'. No pilling, no fading, still thick. The proof is visual.",camera:"Phone — close-up + on-body",angle:"Close-up of fabric (still clean) + full outfit",lighting:"Good, warm",duration:"",tip:"If you actually have a hoodie you've worn for months that still looks great = strongest possible proof."},
      {title:"Slide 4: On-Body — Built to Last",action:"Lifestyle shot — you in the hoodie, looking good. Text: 'Built to last. €45.' The price after the quality proof = value proposition clear.",camera:"Phone — friend-shot",angle:"Full outfit, lifestyle",lighting:"Natural, beautiful",duration:"",tip:"The price on this slide is key. After the quality proof, €45 feels like an investment, not an expense."},
      {title:"Slide 5: CTA — Shop Now",action:"NEWGARMENTS logo + 'Shop Now' + optionally: 'Stop wasting money on fast fashion'. Dark background, clean design.",camera:"Canva/design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"The CTA closes the loop: you've seen the problem, you've seen the proof, now take action."}
    ]
  },
  {
    id:"s5",title:"\"Sold Out 3x\" FOMO Restock",potential:94,difficulty:1,tags:["conversion","FOMO","urgency"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Screenshot of sold out page + 'Sold out 3x this year'",
    hookNote:"FOMO (Fear Of Missing Out) = strongest urgency trigger. You show the product KEEPS selling out → must be good. Restock announcement = direct purchase urgency. 'Before it's gone again' = now or never.",
    textOverlay:"Slide 1: 'Sold out 3x this year 🔥' — Slide 2: 'Finally back in stock' — Slide 3: '460 GSM — double stitched — boxy fit' — Slide 4: '€45 — before it's gone again' — Slide 5: 'Shop Now — link in bio'",
    cta:"Shop Now via Spark Ad — urgency",
    why:"FOMO is the #2 purchase trigger after price anchoring. If something sells out 3x, there's social proof (others are buying) + scarcity (might sell out again). Urgency + social proof = maximum conversion.",
    psychology:"Social proof: 'if that many people buy it, it must be good'. Scarcity: 'if it keeps selling out, I need to buy NOW'. Loss aversion: the fear of missing out is stronger than the desire to have it.",
    proof:[{brand:"FOMO marketing",detail:"Scarcity + urgency = up to 332% higher conversion in e-commerce studies."},{brand:"Social proof",detail:"'Sold out' = implicit recommendation from thousands of buyers."},{brand:"Restock urgency",detail:"'Back in stock' emails/posts have the highest CTR of all e-commerce communication."}],
    equipment:["Screenshot of 'sold out' page (own site or mocked)","Product hero shot","Detail photos","Logo + price + urgency text"],
    caption:"finally back 🔓",
    audio:"Hype/anticipation trending sound",
    firstSlide:"Screenshot of sold out product page. Text: 'Sold out 3x this year 🔥'",
    backedBy:"FOMO psychology (+332% conversion), social proof ('if everyone buys...'), restock urgency",
    sourceLinks:[{label:"Sold Out Restock TikTok",url:"https://www.tiktok.com/discover/sold-out-restock-fashion"},{label:"Back In Stock Hype",url:"https://www.tiktok.com/discover/back-in-stock-hoodie"}],
    goal:"CONVERSION with urgency. 'Buy NOW before it's gone again.'",
    imageRules:"Slide 1 = screenshot of sold out page (real or mocked). Slide 2 = product hero shot (the reveal). Slide 3 = detail collage. Slide 4 = on-body + price. Slide 5 = logo + CTA.",
    steps:[
      {title:"Slide 1: FOMO — Sold Out",action:"Screenshot of your product page with 'SOLD OUT' badge. Or make a collage of 3 sold out screenshots. Text: 'Sold out 3x this year 🔥'. This triggers instant FOMO.",camera:"Screenshot of webshop",angle:"Full page screenshot",lighting:"N/A",duration:"3 min",tip:"If you've actually sold out before = use that. Otherwise mock it up with your site."},
      {title:"Slide 2: The Reveal — Back in Stock",action:"Product hero shot — NEWGARMENTS hoodie, best possible photo. Text: 'Finally back in stock'. This is the relief after the FOMO. The viewer wants to grab it NOW.",camera:"Phone or product photo",angle:"Hero shot — clean, aspirational",lighting:"Good, premium feel",duration:"",tip:"The transition from 'sold out' screenshot to premium product photo = visual payoff."},
      {title:"Slide 3: Details — Why It Sells Out",action:"Collage of detail shots: fabric thickness, double stitching, label, boxy fit. Text: '460 GSM — double stitched — boxy fit'. Gives the REASON why it keeps selling out.",camera:"Phone — close-up details",angle:"Detail collage (3-4 photos in grid)",lighting:"Good light on details",duration:"",tip:"The specs explain WHY it sells out. It's not random — the product is just better."},
      {title:"Slide 4: Urgency — Price + Scarcity",action:"On-body lifestyle shot + price. Text: '€45 — before it's gone again'. The urgency is now double: price is good + might sell out again.",camera:"Phone — friend-shot",angle:"Full outfit, lifestyle",lighting:"Natural",duration:"",tip:"'Before it's gone again' = urgency without being pushy."},
      {title:"Slide 5: CTA — Buy Now",action:"Logo + 'Shop Now — link in bio' or 'Tap to shop ⬇️'. Direct CTA with urgency context from the previous slides.",camera:"Canva/design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"After 4 slides of FOMO + proof + urgency, the CTA is a no-brainer."}
    ]
  },
  {
    id:"s6",title:"\"1 Hoodie, 3 Fits\" Versatility Value",potential:93,difficulty:1,tags:["conversion","styling","versatility"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Outfit 1 + '1 hoodie'",
    hookNote:"Proving versatility = proving value. 3 completely different outfits with the SAME hoodie = '€45 / 3 fits = €15 per look'. Value framing. Plus: styling content = highest save rate = algorithm boost for your Spark Ad.",
    textOverlay:"Slide 1: '1 hoodie' — Slide 2: '3 fits' — Slide 3: 'endless possibilities' — Slide 4: 'NEWGARMENTS 460 GSM — €45' — Slide 5: 'Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Versatility = value. If 1 hoodie gives 3+ looks, it's worth the investment. Styling content is the #1 most-saved format on TikTok = algorithm boost. Saves = more Spark Ad reach.",
    psychology:"Value framing: €45 for 1 thing sounds like an expense. €45 for 3+ outfits sounds like a deal. By showing versatility, you change the perception from 'another hoodie' to 'wardrobe essential'.",
    proof:[{brand:"Styling content",detail:"#1 most-saved carousel format on TikTok. People bookmark to copy outfits."},{brand:"Gymshark",detail:"5.6M views on 1 carousel with outfit variations. 50+ consecutive carousels."},{brand:"Value framing",detail:"Showing versatility = +40% higher purchase consideration."}],
    equipment:["1 NEWGARMENTS hoodie","3 completely different outfits (pants, shoes, accessories)","Same background/location for consistency"],
    caption:"1 hoodie. 3 fits. 💰",
    audio:"Upbeat trending sound",
    firstSlide:"Outfit 1 (casual streetwear) with large text '1 hoodie'",
    backedBy:"#1 most-saved format, Gymshark (5.6M views), value framing psychology",
    sourceLinks:[{label:"1 Hoodie Multiple Fits",url:"https://www.tiktok.com/discover/1-hoodie-multiple-outfits"},{label:"Gymshark Carousel Account",url:"https://www.tiktok.com/@gymshark"},{label:"Outfits Of The Week",url:"https://www.tiktok.com/discover/Outfits-Of-the-Week"}],
    goal:"CONVERSION via value framing. '€45 for 3 looks' = deal.",
    imageRules:"3 outfit photos must look COMPLETELY DIFFERENT. Same hoodie but different vibes (casual, streetwear, dressed up). Same background = focus on outfit differences. Slides 4-5 = product + CTA.",
    steps:[
      {title:"Slide 1: Outfit 1 — Casual",action:"NEWGARMENTS hoodie + jeans + sneakers. Relaxed, everyday. Text: '1 hoodie' — big, bold. This is the hook: what can you do with 1 hoodie?",camera:"Phone — mirror selfie or friend-shot",angle:"Full body, same position as slides 2-3",lighting:"Consistent",duration:"",tip:"Same background for all 3 outfits so the difference in OUTFIT is clear."},
      {title:"Slide 2: Outfit 2 — Streetwear",action:"Same hoodie + cargo pants + Dunks + cap. Streetwear vibe. Text: '3 fits' — the promise is being delivered. Completely different vibe than slide 1.",camera:"Phone — same position",angle:"SAME angle as slide 1",lighting:"SAME as slide 1",duration:"",tip:"The difference must be HUGE. Not the same jeans in a different color — completely different vibe."},
      {title:"Slide 3: Outfit 3 — Elevated",action:"Same hoodie + trousers + loafers or boots. Dressed up. Text: 'endless possibilities'. Shows the hoodie can also go dressy.",camera:"Phone — same position",angle:"SAME angle",lighting:"SAME",duration:"",tip:"The 'elevated' look surprises. A hoodie with trousers = unexpected but fire."},
      {title:"Slide 4: Product + Price",action:"Flat lay of the hoodie + close-up details. Text: 'NEWGARMENTS 460 GSM — €45'. The price after 3 outfits = value framing.",camera:"Phone — flat lay",angle:"Bird's eye",lighting:"Clean, well-lit",duration:"",tip:"After 3 outfits, €45 feels like a deal. €45 / 3 looks = €15 per outfit."},
      {title:"Slide 5: CTA",action:"Logo + 'Shop Now ⬇️' + optionally all 3 colorways side by side. Dark background.",camera:"Canva/design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"Optional: show multiple colorways. '6 colorways = 18 fits' = even more value."}
    ]
  },
  {
    id:"s7",title:"\"TikTok Made Me Buy It\" UGC Review",potential:92,difficulty:1,tags:["conversion","review","UGC-style"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Opening package + 'The hoodie TikTok made me buy'",
    hookNote:"UGC-style review format. Feels like a real review, not an ad. Unboxing → first impressions → details → verdict → CTA. UGC outperforms branded content by +55% ROI. The 'TikTok made me buy it' frame = social proof.",
    textOverlay:"Slide 1: 'The hoodie TikTok made me buy' — Slide 2: '460 GSM is no joke 😳' — Slide 3: 'The fit is crazy' — Slide 4: 'Double stitched everything' — Slide 5: '€45 — worth every cent'",
    cta:"Shop Now via Spark Ad",
    why:"UGC-style = +55% ROI vs branded. 'TikTok made me buy it' = social proof (if TikTok recommends it, it must be good). Review format = lowest ad resistance. Every slide is a 'proof' point.",
    psychology:"Third-party validation: a 'review' feels more objective than a brand talking about itself. The 'TikTok made me buy it' frame implies OTHERS already bought it. Social proof + review = maximum persuasion.",
    proof:[{brand:"#tiktokmademebuyit",detail:"72.5 BILLION views. The most powerful social commerce hashtag ever."},{brand:"UGC ROI",detail:"+55% ROI vs branded content. Unbranded UGC = +19% better than branded."},{brand:"Review format",detail:"Reviews = lowest ad resistance. Feels like info, not an ad."}],
    equipment:["NEWGARMENTS package (wrapped)","Hoodie for unboxing/reveal","On-body photos","Detail close-ups"],
    caption:"no cap this is insane",
    audio:"Trending review/reaction sound",
    firstSlide:"Hands opening a package + text 'The hoodie TikTok made me buy'",
    backedBy:"#tiktokmademebuyit (72.5B views), UGC +55% ROI, review = lowest ad resistance",
    sourceLinks:[{label:"TikTok Made Me Buy It Fashion",url:"https://www.tiktok.com/discover/tiktok-made-me-buy-it-hoodie"},{label:"Hoodie Review TikTok",url:"https://www.tiktok.com/discover/hoodie-review-tiktok"},{label:"Unboxing Streetwear",url:"https://www.tiktok.com/discover/unboxing-streetwear-haul"}],
    goal:"CONVERSION via UGC-style review. Feels like a real recommendation, not an ad.",
    imageRules:"ALL photos must look like they were taken by a CUSTOMER, not the brand. Phone-shot, casual setting, not too perfect. Must feel like a 'real review'. No studio, no professional editing.",
    steps:[
      {title:"Slide 1: Unboxing — The Hook",action:"Hands opening the NEWGARMENTS package. Or package just opened with hoodie inside. Text: 'The hoodie TikTok made me buy'. UGC feel — like a real customer.",camera:"Phone — top-down or POV",angle:"Hands + package, casual",lighting:"Room light — not too perfect",duration:"",tip:"Must look like a REAL unboxing by a customer, not a brand shoot."},
      {title:"Slide 2: First Impression — Thickness",action:"Holding hoodie out of the packaging. Show the THICKNESS — fold it, press it, show the weight. Text: '460 GSM is no joke 😳'. The reaction must feel genuine.",camera:"Phone",angle:"Holding hoodie up, showing thickness",lighting:"Casual",duration:"",tip:"Squeeze the fabric and let it spring back. 460 GSM is VISIBLY thick. That's your strongest visual."},
      {title:"Slide 3: On-Body — The Fit",action:"Mirror selfie or friend-shot in the hoodie. Full outfit. Text: 'The fit is crazy'. The viewer sees how it DRAPES — boxy, oversized, just right.",camera:"Phone — mirror selfie",angle:"Full body",lighting:"Natural",duration:"",tip:"The fit is the 2nd USP after thickness. Boxy oversized = what Gen Z wants. Show it."},
      {title:"Slide 4: Details — Quality Proof",action:"Close-up of double stitching, label, ribbing. Text: 'Double stitched everything'. Every detail = proof that it's premium.",camera:"Phone — close-up",angle:"Macro details",lighting:"Good light",duration:"",tip:"Details you normally don't see in ads = credibility. It feels like an HONEST review."},
      {title:"Slide 5: Verdict + CTA",action:"Another on-body shot or flat lay. Text: '€45 — worth every cent' + 'Shop Now ⬇️'. The verdict = positive. The price = fair. The CTA = clear.",camera:"Phone",angle:"Lifestyle or flat lay",lighting:"Good",duration:"",tip:"'Worth every cent' after all the proof = credible conclusion. Not 'BUY NOW' but 'worth it'."}
    ]
  },
  {
    id:"s8",title:"\"Expectation vs Reality\" Positive Twist",potential:91,difficulty:1,tags:["conversion","surprise","contrast"],platforms:["TikTok Spark Ad"],duration:"4 slides",
    hook:"Generic hoodie stock photo + 'What you expect for €45'",
    hookNote:"Expectation vs reality — but with a POSITIVE twist. Normally 'reality' is worse than expectation. Here it's BETTER. The surprise = dopamine hit. The viewer thinks 'wait, that's really €45?'",
    textOverlay:"Slide 1: 'What you expect for €45:' — Slide 2: 'What you actually get:' — Slide 3: '460 GSM — premium heavyweight' — Slide 4: '€45 — Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Expectation vs reality is one of the most viral TikTok formats. The POSITIVE twist is unexpected — normally reality is a disappointment. That surprise = stronger emotional response = more shares and saves.",
    psychology:"Pattern disruption: the viewer EXPECTS a disappointment (that's how this format normally works). The positive surprise = dopamine spike. That unexpected feeling = higher recall and share rate.",
    proof:[{brand:"Expectation vs reality",detail:"Top 5 most viral TikTok formats. Billions of views."},{brand:"Positive twist",detail:"Unexpectedly positive = stronger emotional response than expected positive."},{brand:"Price surprise",detail:"€45 for premium quality = 'too good to be true' → curiosity click."}],
    equipment:["Generic/basic hoodie photo (stock or own)","NEWGARMENTS hoodie premium shots","Detail close-ups","Logo + CTA"],
    caption:"plot twist 😳",
    audio:"Reveal/transformation trending sound",
    firstSlide:"Boring, generic hoodie photo (think: webshop stock photo). Text: 'What you expect for €45:'",
    backedBy:"Expectation vs reality (billions of views), positive twist psychology, price surprise",
    sourceLinks:[{label:"Expectation vs Reality Fashion",url:"https://www.tiktok.com/discover/expectation-vs-reality-fashion"},{label:"What You Get For The Price",url:"https://www.tiktok.com/discover/what-you-get-for-the-price-hoodie"}],
    goal:"CONVERSION via positive surprise. 'Wait, THIS is €45?' → Shop Now.",
    imageRules:"Slide 1 = INTENTIONALLY BORING (generic hoodie, bad photo). Slide 2 = PREMIUM (NEWGARMENTS, beautiful photo). The contrast must SHOCK. Slides 3-4 = details + CTA.",
    steps:[
      {title:"Slide 1: The Expectation — Boring",action:"A boring, generic hoodie. Stock photo feel. Thin, basic, nothing special. Text: 'What you expect for €45:'. The viewer thinks: 'yeah, that's about right for €45.'",camera:"Intentionally bad/boring photo or stock",angle:"Flat, boring",lighting:"Bad/normal — make it look 'meh'",duration:"3 min",tip:"The more boring slide 1 looks, the bigger the impact of slide 2. Make it INTENTIONALLY ugly."},
      {title:"Slide 2: The Reality — Premium",action:"NEWGARMENTS hoodie on person. Best possible photo. Premium, aspirational, fire. Text: 'What you actually get:'. The SWITCH must be felt. From boring to 🔥.",camera:"Phone — best possible shot",angle:"Full outfit, styled",lighting:"Warm, beautiful, perfect",duration:"",tip:"This is your 'holy shit' moment. The contrast with slide 1 sells the product."},
      {title:"Slide 3: Proof — Details",action:"Close-up collage: thick fabric, double stitching, premium label. Text: '460 GSM — premium heavyweight'. The proof that the 'reality' is genuinely that good.",camera:"Phone — close-ups",angle:"Detail collage",lighting:"Good light",duration:"",tip:"The details prove it's not clickbait. It IS genuinely premium for €45."},
      {title:"Slide 4: CTA — Price + Action",action:"Logo + '€45 — Shop Now ⬇️'. After the surprise, the viewer is curious. The CTA captures that curiosity.",camera:"Canva/design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"REPEATING the price after the premium proof reinforces 'too good to be true' → must check it out."}
    ]
  },
  {
    id:"s9",title:"\"Rate This Drop 1-10\" Colorway Showcase",potential:90,difficulty:1,tags:["conversion","engagement","product-showcase"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"All colorways laid out + 'Rate this drop 1-10'",
    hookNote:"Engagement + conversion combo. The rating question triggers comments (algorithm fuel for Spark Ad), while the colorway showcase drives product awareness. Comments = Spark Ad reach. Price at the end = conversion.",
    textOverlay:"Slide 1: 'Rate this drop 1-10 🔥' — Slide 2: '[Colorway name] — €45' (per colorway) — Slide 3: close-up detail — Slide 4: on-body — Slide 5: 'All colors — Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Dual purpose: engagement (comments drive Spark Ad performance) + conversion (product showcase + price). Everyone types a number = lowest friction comment. Every comment = more reach. Colorway lineup = choice = purchase consideration.",
    psychology:"Gamification: giving a number is IRRESISTIBLE. It's too easy not to do. Choice architecture: seeing all options at once prevents choice overload. Price per colorway = direct purchase framing.",
    proof:[{brand:"Rating comments",detail:"'Rate 1-10' = most comments of all caption types. 2.9x more than video."},{brand:"Colorway showcase",detail:"Showing multiple options = higher purchase consideration."},{brand:"Spark Ad fuel",detail:"Every comment = engagement signal that improves Spark Ad performance."}],
    equipment:["All hoodie colorways","Flat lay or hanger setup","On-body photos per colorway","Logo + CTA"],
    caption:"rate this drop 1-10 🔥",
    audio:"Hype trending sound",
    firstSlide:"All colorways side by side laid out. Text: 'Rate this drop 1-10 🔥'",
    backedBy:"Rating = most comments, colorway showcase = higher conversion, Spark Ad comment fuel",
    sourceLinks:[{label:"Rate This Drop Fashion",url:"https://www.tiktok.com/discover/rate-this-drop"},{label:"Rate My Outfit 1-10",url:"https://www.tiktok.com/discover/rate-my-outfit-1-10"},{label:"Colorway Lineup Streetwear",url:"https://www.tiktok.com/discover/hoodie-colorway-lineup"}],
    goal:"ENGAGEMENT + CONVERSION. Comments drive Spark Ad reach, colorways drive purchases.",
    imageRules:"Slide 1 = all colorways in 1 image (flat lay or hangers). Slides 2-3 = individual colorways + details. Slide 4 = on-body. Slide 5 = logo + all colors + CTA. Clean, consistent editing.",
    steps:[
      {title:"Slide 1: The Lineup — All Colorways",action:"All hoodie colorways side by side. Flat lay or on hangers. Text: 'Rate this drop 1-10 🔥'. This is the hook — the full lineup = visually impactful.",camera:"Phone — from above or straight on",angle:"All colorways visible in 1 shot",lighting:"Clean, even",duration:"",tip:"Make sure EVERY color is clearly visible. Not too much shadow."},
      {title:"Slide 2: Individual Colorways",action:"2-3 colorways individually or in small group. Text per item: '[color name] — €45'. Price with every colorway = direct purchase framing.",camera:"Phone — flat lay per colorway",angle:"Close-up per hoodie",lighting:"Consistent",duration:"",tip:"Price on every slide = the viewer gets used to the idea of buying, not just looking."},
      {title:"Slide 3: Detail Shot",action:"Close-up of fabric, stitching, label. Text: '460 GSM — double stitched'. The specs after the visual lineup = quality proof.",camera:"Phone — macro",angle:"Detail close-ups",lighting:"Good",duration:"",tip:"The quality justifies the price. Show it, don't tell it."},
      {title:"Slide 4: On-Body",action:"Someone wearing the best-selling colorway. Lifestyle shot. Show the fit. No text needed — the photo speaks.",camera:"Phone — friend-shot",angle:"Full outfit",lighting:"Natural",duration:"",tip:"From flat lay to on-body = the viewer can imagine how it looks on THEM."},
      {title:"Slide 5: CTA — Shop All Colors",action:"Logo + all colorway swatches/photos small + 'Shop Now ⬇️ — All colors available'. The close with ALL options + clear CTA.",camera:"Canva/design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"All colors on the last slide = 'there's always one for you'. No excuse not to buy."}
    ]
  },
  {
    id:"s10",title:"\"Things Worth The Money\" Listicle",potential:89,difficulty:1,tags:["conversion","listicle","positioning"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Aesthetic collage of 'worth it' items + title",
    hookNote:"Listicle format — your hoodie alongside other 'worth it' items (good coffee, quality shoes, etc). Positioning: your product belongs in 'things worth the money'. High save rate + conversion. Wishlist energy with purchase intent.",
    textOverlay:"Slide 1: 'Things that are actually worth the money 💰' — Slide 2: 'Good coffee ☕' — Slide 3: 'A heavyweight hoodie that lasts — NEWGARMENTS' — Slide 4: '460 GSM — €45 — built to last' — Slide 5: 'Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Listicle format = high save rate (people bookmark lists). Your product next to 'worth it' items = premium positioning WITHOUT claiming premium. The context does the work.",
    psychology:"Context effect: by placing your hoodie next to 'worth it' items, it automatically gets associated with 'quality worth the price'. Associative framing = stronger perception than direct claims.",
    proof:[{brand:"Listicle format",detail:"Top 3 most-saved content types on TikTok. High bookmark rate."},{brand:"Associative framing",detail:"Product next to premium items = premium perception without premium price."},{brand:"'Worth the money'",detail:"Trending format with high purchase conversion — people actively search for 'worth it' recommendations."}],
    equipment:["Aesthetic photos of 'worth it' items (coffee, shoes, etc.)","NEWGARMENTS hoodie photos","Detail close-ups","Logo + CTA"],
    caption:"worth every penny 💰",
    audio:"Soft, appreciative trending sound",
    firstSlide:"Aesthetic collage: good coffee, quality shoes, book — text: 'Things that are actually worth the money 💰'",
    backedBy:"Listicle = top 3 most-saved, associative framing psychology, 'worth the money' trending format",
    sourceLinks:[{label:"Things Worth The Money TikTok",url:"https://www.tiktok.com/discover/things-that-are-worth-the-money"},{label:"Worth The Investment Fashion",url:"https://www.tiktok.com/discover/wardrobe-essentials-worth-the-money"}],
    goal:"CONVERSION via associative framing. Your hoodie = 'worth it' category.",
    imageRules:"Slide 1 = aesthetic intro (other items, not your product). Slide 2 = another 'worth it' item. Slide 3 = YOUR product (the star). Slide 4 = details + price. Slide 5 = CTA. Consistent warm, premium aesthetic on all slides.",
    steps:[
      {title:"Slide 1: Title — Worth The Money",action:"Aesthetic photo of 'worth it' things (coffee, book, plant, quality shoe). Text: 'Things that are actually worth the money 💰'. Clean, warm aesthetic.",camera:"Phone or curated images",angle:"Flat lay or mood board",lighting:"Warm, premium",duration:"5 min",tip:"First slide must look like a Pinterest board. Aesthetic = saves."},
      {title:"Slide 2: Another 'Worth It' Item",action:"One other item that's 'worth it' (e.g. good coffee, quality shoes, skincare). Text: 'Good coffee ☕' or 'Quality shoes'. This builds the list BEFORE your product comes.",camera:"Aesthetic photo",angle:"Clean, beautiful",lighting:"Warm",duration:"3 min",tip:"This item must be CREDIBLY 'worth it'. It builds context for your product."},
      {title:"Slide 3: YOUR Product — The Star",action:"NEWGARMENTS hoodie on person or flat lay. Text: 'A heavyweight hoodie that actually lasts — NEWGARMENTS'. This is your MOMENT — your product in the 'worth it' category.",camera:"Phone — best shot",angle:"Lifestyle or flat lay, premium feel",lighting:"Warm, consistent with previous slides",duration:"",tip:"The transition must be smooth. Your product BELONGS in this list. Not forced."},
      {title:"Slide 4: Proof + Price",action:"Detail shots: fabric thickness, stitching, label. Text: '460 GSM — €45 — built to last'. The specs + price prove WHY it's worth it.",camera:"Phone — close-up",angle:"Detail collage",lighting:"Good",duration:"",tip:"The price (€45) in the 'worth it' context feels like an investment, not an expense."},
      {title:"Slide 5: CTA",action:"Logo + 'Shop Now ⬇️'. Clean, consistent with the aesthetic of the entire slideshow.",camera:"Canva/design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"The CTA must match the premium, calm aesthetic. Not screaming."}
    ]
  },
  {
    id:"s11",title:"\"Winter Essentials Under €50\" Curated List",potential:88,difficulty:1,tags:["conversion","seasonal","listicle"],platforms:["TikTok Spark Ad"],duration:"6 slides",
    hook:"Title card: 'Winter essentials that won't break the bank'",
    hookNote:"Seasonal essentials format. Your hoodie as 1 of 4-5 items in a curated list. High save rate (people bookmark seasonal content). Your product among other items = less ad-feel, more editorial.",
    textOverlay:"Slide 1: 'Winter essentials under €50 🧊' — Slide 2: 'Beanie — €15' — Slide 3: 'NEWGARMENTS 460 GSM Hoodie — €45 ⭐' — Slide 4: 'Cargo pants — €40' — Slide 5: 'Total outfit: under €100' — Slide 6: 'Shop the hoodie ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Seasonal content = timing relevance. Essentials list = save trigger. Your product as part of a curated outfit = editorial feel, not ad feel. 'Under €50' = budget-friendly = broad audience.",
    psychology:"List format = save reflex. Seasonal relevance = 'I need this NOW'. Budget framing ('under €50', 'under €100 total') = no price objection. Your hoodie is the HIGHLIGHTED item = star of the list.",
    proof:[{brand:"Seasonal essentials",detail:"Timing-relevant content = 2-3x higher engagement than evergreen."},{brand:"Listicle saves",detail:"Lists = #1 most-saved format on TikTok."},{brand:"Budget framing",detail:"'Under €X' = no price objection. Everyone feels addressed."}],
    equipment:["Canva for consistent design","Product photos per item","NEWGARMENTS hoodie as highlighted item","Logo + CTA"],
    caption:"winter sorted ❄️",
    audio:"Cozy winter trending sound",
    firstSlide:"Title card in aesthetic typography: 'Winter essentials under €50 🧊'",
    backedBy:"Seasonal timing (+2-3x engagement), listicle save format, budget framing",
    sourceLinks:[{label:"Winter Essentials Under 50",url:"https://www.tiktok.com/discover/winter-essentials-under-50"},{label:"Winter Outfit Essentials",url:"https://www.tiktok.com/discover/winter-outfit-essentials-2026"},{label:"Budget Streetwear Essentials",url:"https://www.tiktok.com/discover/budget-streetwear-essentials"}],
    goal:"CONVERSION via seasonal urgency + curated list positioning.",
    imageRules:"Canva-designed. Consistent aesthetic on all slides. 1 item per slide with name + price. NEWGARMENTS hoodie = highlighted (star/emoji/bigger). Last slide = CTA.",
    steps:[
      {title:"Slide 1: Title Card",action:"'Winter essentials under €50 🧊'. Aesthetic typography on dark background. Canva template 1080x1920. No product — pure promise.",camera:"Canva design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"The title must look EDITORIAL. Not like an ad but like a magazine feature."},
      {title:"Slide 2: Item 1 — Beanie",action:"Photo of a beanie + 'Beanie — €15'. Clean layout, consistent with slide 1 design.",camera:"Product photo",angle:"Clean shot",lighting:"Consistent",duration:"3 min",tip:"Start with a cheap item so the list feels 'budget-friendly'."},
      {title:"Slide 3: Item 2 — NEWGARMENTS (STAR)",action:"NEWGARMENTS hoodie — MORE PROMINENT than other items. Bigger font, ⭐ emoji, or highlight border. Text: 'NEWGARMENTS 460 GSM Hoodie — €45 ⭐'. This is the star.",camera:"Best product photo",angle:"On-body or flat lay",lighting:"Premium feel",duration:"",tip:"This is your product. Make it the OBVIOUS highlight of the list. Bigger, better, more prominent."},
      {title:"Slide 4: Item 3 — Cargo Pants",action:"Photo of cargo pants + 'Cargo pants — €40'. Consistent design. This gives context: complete outfit.",camera:"Product photo",angle:"Clean",lighting:"Consistent",duration:"3 min",tip:"The other items build a complete outfit around YOUR hoodie."},
      {title:"Slide 5: Total — Outfit Complete",action:"All items together in 1 image (flat lay or on-body). Text: 'Total outfit: under €100'. This shows the value of the whole package.",camera:"Phone — flat lay or collage",angle:"All items together",lighting:"Clean",duration:"",tip:"'Under €100 for a complete outfit' = budget-friendly = no excuse."},
      {title:"Slide 6: CTA — Shop the Hoodie",action:"NEWGARMENTS logo + 'Shop the hoodie ⬇️' + €45. Focus on YOUR product — the rest is context. The CTA is specific: shop the hoodie.",camera:"Canva/design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"Specific CTA ('shop the hoodie') converts better than generic ('shop now')."}
    ]
  },
  {
    id:"s12",title:"\"I Wear This Every Day\" Durability Proof",potential:87,difficulty:1,tags:["conversion","durability","social-proof"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Monday outfit + 'I literally wear this every day'",
    hookNote:"Durability proof via daily wear. Same hoodie, different days, still clean. Proves 460 GSM holds up. This is not styling (that's concept 6) — this is QUALITY PROOF through daily use.",
    textOverlay:"Slide 1: 'I literally wear this every day' — Slide 2: 'Monday' — Slide 3: 'Wednesday — still clean' — Slide 4: 'Friday — no pilling, no fading ✅' — Slide 5: '€45 — your daily go-to — Shop Now'",
    cta:"Shop Now via Spark Ad",
    why:"Durability = the #1 objection killer. 'Will it hold up?' is the biggest doubt when buying hoodies online. By SHOWING you wear it every day and it still looks great, you remove that doubt.",
    psychology:"Consistency = proof. If someone wears something EVERY DAY and it's still perfect, that's more convincing than any spec or review. Daily use is the ultimate quality proof.",
    proof:[{brand:"Durability content",detail:"'X months later' content = high conversion. Real wear test = credible proof."},{brand:"Objection handling",detail:"'Will it hold up?' = #1 doubt for online purchases. Daily use proves it."},{brand:"Consistency visual",detail:"Same item, multiple days = visually satisfying + convincing."}],
    equipment:["1 NEWGARMENTS hoodie","Outfit photos on 3-4 different days","Close-up after multiple washes"],
    caption:"daily driver 🤝",
    audio:"Casual daily vibe trending sound",
    firstSlide:"Monday outfit — you in NEWGARMENTS hoodie. Text: 'I literally wear this every day'",
    backedBy:"Durability proof = #1 objection killer, daily wear content, 'X months later' format",
    sourceLinks:[{label:"Hoodie Daily Wear Test",url:"https://www.tiktok.com/discover/hoodie-daily-wear-test"},{label:"Same Hoodie Every Day",url:"https://www.tiktok.com/discover/same-hoodie-every-day"}],
    goal:"CONVERSION via durability proof. Remove doubt → Shop Now.",
    imageRules:"Same hoodie on 3+ days. Different outfits but SAME hoodie. After multiple days: still perfect. Close-up on day 3+ shows no pilling/fading. Consistent lighting.",
    steps:[
      {title:"Slide 1: Monday — Start",action:"Full outfit with NEWGARMENTS hoodie. Fresh, clean. Text: 'I literally wear this every day'. This is the claim — the rest proves it.",camera:"Phone — mirror selfie or friend-shot",angle:"Full body",lighting:"Natural",duration:"",tip:"The hook is the claim. 'Every day' = bold statement you MUST prove."},
      {title:"Slide 2: Wednesday — Still Clean",action:"Same hoodie, different outfit. Text: 'Wednesday'. The point: after 3 days it still looks new.",camera:"Phone",angle:"Full body, different outfit",lighting:"Consistent",duration:"",tip:"Show the hoodies side-by-side if you can. Or make sure the quality looks equally good."},
      {title:"Slide 3: Friday — Proof",action:"Same hoodie, yet another outfit. Text: 'Friday — no pilling, no fading ✅'. This is the moment: 5 days, still perfect.",camera:"Phone",angle:"Full body + close-up of fabric",lighting:"Consistent",duration:"",tip:"A close-up of the fabric on day 5 = proof. Still smooth, no pilling."},
      {title:"Slide 4: Close-Up — Quality After Use",action:"Macro close-up of the fabric after days of wearing. Text: '460 GSM holds up'. No pilling, no warping, still thick.",camera:"Phone — close-up",angle:"Macro fabric detail",lighting:"Good light",duration:"",tip:"This is the 'proof' slide. The fabric after use = your strongest selling point."},
      {title:"Slide 5: CTA — Daily Go-To",action:"Lifestyle shot + '€45 — your daily go-to — Shop Now ⬇️'. The conclusion: this is the hoodie you WANT to wear every day. And it's €45.",camera:"Phone or design",angle:"Lifestyle or graphic",lighting:"Beautiful",duration:"",tip:"'Daily go-to' positions it as essential, not luxury. €45 for something essential = easy buy."}
    ]
  },
  {
    id:"s13",title:"\"Everyone Keeps Asking\" Social Proof",potential:86,difficulty:2,tags:["conversion","social-proof","lifestyle"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Group photo, you in hoodie + 'POV: everyone asking about your hoodie'",
    hookNote:"Social proof via the 'everyone keeps asking' frame. If OTHERS are asking about it, it must be good. This is third-party validation in image form. Other people's curiosity = purchase trigger for the viewer.",
    textOverlay:"Slide 1: 'POV: everyone asking about your hoodie' — Slide 2: 'Where is that from??' — Slide 3: 'NEWGARMENTS' — Slide 4: '460 GSM — €45' — Slide 5: 'Shop Now — be next ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Social proof = the #3 conversion trigger. If others are interested in the product, the viewer wants it too. The 'everyone asking' frame is stronger than a review — it's LIVE reaction.",
    psychology:"Social validation: 'if other people are asking about it, it must be special'. Curiosity transfer: the curiosity of the people in the image transfers to the viewer. FOMO: 'they have it, I don't'.",
    proof:[{brand:"Social proof format",detail:"'Everyone asking' = trending TikTok format for product showcase."},{brand:"Third-party validation",detail:"Reactions from OTHERS are more convincing than your own claims."},{brand:"FOMO trigger",detail:"Others wanting the product = 'I need it too'."}],
    equipment:["Group photos where you're wearing the hoodie","Close-up of label/tag","Product photos","Friends 'reacting' to your hoodie (can be staged)"],
    caption:"they always ask 🤫",
    audio:"Trending hype/flex sound",
    firstSlide:"Group photo — you standing out in NEWGARMENTS hoodie. Text: 'POV: everyone asking about your hoodie'",
    backedBy:"Social proof psychology (#3 conversion trigger), 'everyone asking' trending format",
    sourceLinks:[{label:"Everyone Asking About Your Outfit",url:"https://www.tiktok.com/discover/everyone-asking-about-your-outfit"},{label:"Where Is That From TikTok",url:"https://www.tiktok.com/discover/where-is-that-from-hoodie"}],
    goal:"CONVERSION via social proof. Others want it = you want it.",
    imageRules:"Slide 1 = group photo (you = the only one in the hoodie, standing out). Slide 2 = DM/text screenshot or staged 'where is that from?' reaction. Slide 3 = product reveal. Slide 4 = specs + price. Slide 5 = CTA.",
    steps:[
      {title:"Slide 1: The Scene — Group Photo",action:"You with friends. YOU are wearing the NEWGARMENTS hoodie — it stands out. Text: 'POV: everyone asking about your hoodie'. It's as if everyone is looking at it.",camera:"Phone — group photo, casual",angle:"Group, you central or standing out",lighting:"Casual, social setting",duration:"",tip:"The hoodie must STAND OUT in the group. Other people in basic clothing."},
      {title:"Slide 2: The Reaction — 'Where Is That From?'",action:"Screenshot of DM/text: 'yo where's that hoodie from?' or multiple messages. Or staged: friend pointing at your hoodie. Text: 'Where is that from??'",camera:"Screenshot or staged photo",angle:"N/A or close-up",lighting:"N/A",duration:"3 min",tip:"Real DM screenshots are MORE POWERFUL than staged. If you have them, use them."},
      {title:"Slide 3: The Reveal — NEWGARMENTS",action:"Product shot or label close-up. Text: 'NEWGARMENTS'. The brand reveal. Clean, confident.",camera:"Phone — product or label",angle:"Clean shot",lighting:"Good",duration:"",tip:"The reveal must be CLEAN. Logo/label clear. No long explanation needed."},
      {title:"Slide 4: Specs + Price",action:"Detail collage: fabric, stitching, fit. Text: '460 GSM — €45'. Why they want it: the quality. What it costs: €45.",camera:"Phone — details",angle:"Close-ups",lighting:"Good",duration:"",tip:"After the social proof the viewer is already interested. Specs + price close the deal."},
      {title:"Slide 5: CTA — Be Next",action:"Logo + 'Shop Now — be next ⬇️'. 'Be next' = you can be the next person getting compliments.",camera:"Canva/design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"'Be next' is stronger than just 'Shop Now'. It promises a RESULT, not just a product."}
    ]
  },
  {
    id:"s14",title:"\"Hoodie Tier List\" Ranking Format",potential:85,difficulty:1,tags:["conversion","gamified","viral"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Tier list graphic (S-F tiers) + 'Hoodie tier list'",
    hookNote:"Gamified ranking format. Tier lists are MASSIVE on TikTok — everyone has an opinion. You rank fast fashion as C/D-tier, expensive brands as B-tier, NEWGARMENTS as S-tier. The controversy = comments = Spark Ad fuel. The ranking = product positioning.",
    textOverlay:"Slide 1: 'Hoodie tier list 🏆' — Slide 2: 'C-tier: fast fashion — pills after 2 washes' — Slide 3: 'B-tier: designer — good but €200+' — Slide 4: 'S-TIER: 460 GSM — €45 — NEWGARMENTS' — Slide 5: 'Shop the S-tier ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Tier lists = engagement magnet. EVERYONE reacts to rankings (agree or disagree = comments = algorithm fuel). You position NEWGARMENTS as S-tier with an objective reason (460 GSM for €45). Controversy = virality.",
    psychology:"Gamification: people MUST react to tier lists. It's impossible not to. Anchoring: by ranking fast fashion as C and designer as B, S-tier for your product is logical. The viewer accepts the framing.",
    proof:[{brand:"Tier list format",detail:"Billions of views on TikTok. Everyone reacts = engagement magnet."},{brand:"Gamification",detail:"Rankings trigger automatic reactions. Agree/disagree = comments."},{brand:"Product positioning",detail:"S-tier ranking with objective reasoning = powerful positioning."}],
    equipment:["Tier list template (Canva or tiermaker.com)","Fast fashion hoodie photos","Designer hoodie references","NEWGARMENTS hoodie photos"],
    caption:"the only right answer",
    audio:"Gaming/competitive trending sound",
    firstSlide:"Tier list template with 'Hoodie tier list 🏆' — S to F tiers visible",
    backedBy:"Tier list format (billions of views), gamification psychology, product positioning",
    sourceLinks:[{label:"Tier List Fashion TikTok",url:"https://www.tiktok.com/discover/hoodie-tier-list"},{label:"Fashion Tier List Ranking",url:"https://www.tiktok.com/discover/fashion-tier-list"},{label:"Streetwear Ranking",url:"https://www.tiktok.com/discover/streetwear-tier-list"}],
    goal:"ENGAGEMENT + CONVERSION. Comments = Spark Ad fuel, S-tier ranking = purchase trigger.",
    imageRules:"Slide 1 = tier list graphic (S-F). Slides 2-3 = other tiers with reasoning. Slide 4 = S-TIER with NEWGARMENTS (big, prominent, premium feel). Slide 5 = CTA. Use tier list colors (red = S, orange = A, etc).",
    steps:[
      {title:"Slide 1: Tier List — The Hook",action:"Tier list template with S-F tiers. Text: 'Hoodie tier list 🏆'. Not filled in yet or partially visible. This triggers instant curiosity — 'what's ranked where?'",camera:"Canva/design — tiermaker.com screenshot",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"Tier lists = instant engagement. Everyone scrolls through to see what's ranked where."},
      {title:"Slide 2: C-Tier — Fast Fashion",action:"Fast fashion hoodies in C/D-tier. Photo of thin, pilled hoodie. Text: 'C-tier: fast fashion — pills after 2 washes'. Reason = objective.",camera:"Photo of bad quality hoodie",angle:"N/A",lighting:"N/A",duration:"3 min",tip:"Be specific: 'pills after 2 washes' is a fact, not an opinion. Objective = credible."},
      {title:"Slide 3: B-Tier — Designer",action:"Designer hoodies in B-tier. Text: 'B-tier: designer — good quality but €200+'. The reason: good but too expensive. This sets the stage for your S-tier.",camera:"Stock/reference photos",angle:"N/A",lighting:"N/A",duration:"3 min",tip:"B-tier for designer = controversial = comments. People will debate = algorithm fuel."},
      {title:"Slide 4: S-TIER — NEWGARMENTS",action:"NEWGARMENTS hoodie in S-tier. BIG, prominent, premium visual. Text: 'S-TIER: 460 GSM — €45 — NEWGARMENTS'. The reason: premium quality, fair price.",camera:"Best product photo + tier list frame",angle:"Premium, hero shot",lighting:"Best possible",duration:"",tip:"This is the moment. S-tier with OBJECTIVE reason (460 GSM + €45). Not arrogant but factual."},
      {title:"Slide 5: CTA — Shop The S-Tier",action:"Logo + 'Shop the S-tier ⬇️'. The CTA plays into the tier list framing. You're not buying a hoodie — you're buying S-tier.",camera:"Canva/design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"'Shop the S-tier' is stronger than 'Shop Now'. It plays into the ranking = aspiration."}
    ]
  },
  {
    id:"s15",title:"\"Upgrade Your Basics\" Wardrobe Glow-Up",potential:84,difficulty:1,tags:["conversion","transformation","aspirational"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Closet full of cheap basics + 'Your wardrobe deserves better'",
    hookNote:"Wardrobe upgrade format. From fast fashion chaos → premium essentials. The viewer recognizes their own closet full of H&M basics. The NEWGARMENTS hoodie = the upgrade. Aspirational but attainable (€45).",
    textOverlay:"Slide 1: 'Your wardrobe deserves better 👀' — Slide 2: 'Stop buying €15 hoodies that fall apart after 3 washes' — Slide 3: 'Upgrade to 460 GSM' — Slide 4: 'Premium without the premium price — €45' — Slide 5: 'Start your upgrade ⬇️ Shop Now'",
    cta:"Shop Now via Spark Ad",
    why:"Wardrobe upgrade = aspirational but ATTAINABLE. Everyone wants better clothes but thinks it's expensive. €45 makes it attainable. The 'ditch fast fashion' angle resonates with Gen Z's sustainability values.",
    psychology:"Aspirational gap: the viewer sees their CURRENT wardrobe (meh) and their DESIRED wardrobe (premium). The product is the bridge. €45 = low barrier to start 'upgrading'. 'Start with 1 piece' = less overwhelming.",
    proof:[{brand:"Wardrobe upgrade",detail:"'Capsule wardrobe' and 'wardrobe essentials' = trending on TikTok."},{brand:"Quality over quantity",detail:"Gen Z trend: buy less but better. Anti-fast-fashion movement."},{brand:"Attainable aspiration",detail:"€45 = fancy coffee equivalent per month. Reframing = 'it costs nothing'."}],
    equipment:["Photo of 'before' closet (messy, cheap basics)","Photo of 'after' closet (organized, premium pieces)","NEWGARMENTS hoodie prominently","Logo + CTA"],
    caption:"quality over quantity always",
    audio:"Transformation/glow-up trending sound",
    firstSlide:"Messy closet full of thin, cheap basics. Text: 'Your wardrobe deserves better 👀'",
    backedBy:"Capsule wardrobe trend, quality over quantity Gen Z movement, attainable aspiration",
    sourceLinks:[{label:"Wardrobe Upgrade TikTok",url:"https://www.tiktok.com/discover/wardrobe-upgrade-essentials"},{label:"Quality Over Quantity Fashion",url:"https://www.tiktok.com/discover/quality-over-quantity-fashion"},{label:"Capsule Wardrobe Streetwear",url:"https://www.tiktok.com/discover/capsule-wardrobe-streetwear"}],
    goal:"CONVERSION via aspirational upgrade. From cheap basics → premium essentials. Start at €45.",
    imageRules:"Slide 1 = BEFORE (messy, cheap, meh). Slide 2 = amplify the problem. Slide 3 = the solution (NEWGARMENTS). Slide 4 = price (attainable). Slide 5 = CTA. Visual contrast between 'before' and 'after'.",
    steps:[
      {title:"Slide 1: Before — The Mess",action:"Photo of a messy closet full of thin basics, discolored t-shirts, pilled hoodies. Text: 'Your wardrobe deserves better 👀'. The viewer recognizes this — it's THEIR closet.",camera:"Phone — own closet or staged",angle:"Open closet, everything visible",lighting:"Normal — don't make it look good",duration:"3 min",tip:"The messier and 'sadder' it looks, the stronger the motivation to upgrade."},
      {title:"Slide 2: The Problem — Fast Fashion Fail",action:"Close-up of pilled, thin hoodies. Text: 'Stop buying €15 hoodies that fall apart after 3 washes'. Make the problem tangible with proof.",camera:"Phone — close-up bad quality",angle:"Detail of pilling, holes, fading",lighting:"Bright",duration:"3 min",tip:"This is agitation — making the problem FELT. The viewer thinks: 'shit, that's my hoodie'."},
      {title:"Slide 3: The Upgrade — NEWGARMENTS",action:"NEWGARMENTS hoodie — premium shot. On person or flat lay. Text: 'Upgrade to 460 GSM'. The switch from 'bad' to 'good' quality is visually clear.",camera:"Phone — best possible shot",angle:"Premium, clean",lighting:"Warm, beautiful",duration:"",tip:"The contrast with slides 1-2 = the 'I want this' trigger. From ugly to beautiful."},
      {title:"Slide 4: Price — Attainable",action:"Product + price prominent. Text: 'Premium without the premium price — €45'. The price makes it attainable. It's not a dream — it's €45.",camera:"Product photo + price overlay",angle:"Clean",lighting:"Good",duration:"",tip:"€45 after the 'upgrade' story feels like a small investment in yourself. Not like an expense."},
      {title:"Slide 5: CTA — Start Your Upgrade",action:"Logo + 'Start your upgrade ⬇️ Shop Now'. 'Start' implies this is just the BEGINNING — you're building a better wardrobe. The hoodie is step 1.",camera:"Canva/design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"'Start your upgrade' is stronger than 'Shop Now'. It promises a JOURNEY, not just a purchase."}
    ]
  }
];
