const SLIDESHOW_IDEAS = [
  {
    id:"s1",title:"\"What Do You Want?\" — \"Nothing...\"",potential:97,difficulty:1,tags:["dialogue","relatable","saves"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"What do you want for your birthday?",
    hookNote:"Dialogue carousel met B&W silhouette → product reveal. De comedic contrast tussen 'nothing' en je product = massale saves. Viewers bookmarken als gift reference. Werkt voor elke gelegenheid (verjaardag, Kerst, Valentijn).",
    textOverlay:"Slide 1: 'What do you want for your birthday?' — Slide 2: 'nothing..' — Slide 3: 'well maybe...' — Slide 4: (geen tekst, hoodie spreekt) — Slide 5: 'ok maybe this one thing'",
    cta:"Spark Ad link",
    why:"Dialogue format voelt persoonlijk, niet promotioneel. De reveal positioneert het product als een geheim verlangen. B&W → kleur contrast = visueel scroll-stoppend op de FYP. Birthday wishlist = extreem hoge save rate.",
    psychology:"Relatable humor disarmt ad resistance. 'Nothing' zeggen en dan toch willen = universeel herkenbaar. De B&W silhouette stopt de scroll door pattern interruption in een kleurrijk FYP feed.",
    proof:[{brand:"Wishlist TikTok",detail:"Birthday/Christmas wishlist slideshows = hoogste save rate van alle carousel formats. Mensen bookmarken als gift reference."},{brand:"Dialogue carousels",detail:"Conversational text overlays = 2.9x meer comments dan video format."},{brand:"B&W aesthetic",detail:"Dark/moody aesthetic = peak streetwear visual language. Valt op tussen kleurrijke FYP content."}],
    equipment:["B&W/silhouette foto's van model","Product foto's (hoodie in kleur)","Phone camera","Moody setting (donker, atmospheric)","Canva of CapCut voor text overlays"],
    caption:"nothing..",
    audio:"Soft emotional lo-fi of trending ambient",
    firstSlide:"Moody B&W silhouette met tekst 'What do you want for your birthday?'",
    backedBy:"Wishlist trend (miljarden views), dialogue carousel format (2.9x comments), B&W aesthetic (trending)",
    goal:"Saves + comments. Gift reference content dat gebookmarkt wordt.",
    imageRules:"B&W of hoog-contrast silhouette foto's. Moody, atmospheric. Product reveal op slides 3-5 = enige kleur moment. Film grain, schaduwen, dramatisch licht. Phone-shot.",
    steps:[
      {title:"Slide 1: De Vraag",action:"B&W silhouette foto van jezelf/model. Tekst overlay: 'What do you want for your birthday?' Groot, bold, leesbaar.",camera:"Phone, hoog contrast licht (raam + donkere kamer)",angle:"Silhouette — backlit zodat je alleen de shape ziet",lighting:"Backlit — licht achter het model",duration:"",tip:"De B&W stopt de scroll op de kleurrijke FYP."},
      {title:"Slide 2: 'Nothing..'",action:"Zelfde B&W style, andere pose. Tekst: 'nothing..' Klein, understated — contrast met de grote vraag op slide 1.",camera:"Phone",angle:"Andere hoek dan slide 1",lighting:"Zelfde moody B&W",duration:"",tip:"Het 'nothing' is het relatable moment dat iedereen herkent."},
      {title:"Slide 3: De Twijfel",action:"PLOTSELINGE KLEUR — NEWGARMENTS hoodie op hanger, flatlay, of held up. Tekst: 'well maybe...'",camera:"Phone",angle:"Product-focused maar casual",lighting:"Warm licht — contrast met de koude B&W",duration:"",tip:"De kleur-switch is de visual payoff. Dit is het moment."},
      {title:"Slide 4: De Reveal",action:"Persoon DRAAGT de hoodie. Real setting. Geen tekst — laat de hoodie spreken.",camera:"Phone, friend-shot of timer",angle:"Full outfit zichtbaar",lighting:"Natuurlijk licht, real setting",duration:"",tip:"Dit is de 'ik wil dit' slide. Moet er native uitzien, als een friend's post."},
      {title:"Slide 5: Detail Close-Up",action:"Close-up van label, stiksel, 460 GSM dikte. Optioneel: 'ok maybe this one thing'",camera:"Phone, macro-ish",angle:"Detail — fabric, label, stitching",lighting:"Natuurlijk",duration:"",tip:"Kwaliteit bewijs zonder het uit te leggen. De dikte spreekt voor zich."}
    ]
  },
  {
    id:"s2",title:"Boom Clap Text Sync",potential:95,difficulty:2,tags:["text-sync","beat-drop","trending"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Tekst op elke beat drop",
    hookNote:"Charli XCX 'Boom Clap' — trending NOW maart 2026. Tekst verschijnt op elke beat. Ritmische audiovisuele alignment triggert dopamine. Viewers kijken tot het einde en replayen.",
    textOverlay:"Bold tekst per slide, synced op de beat. Kort: 2-4 woorden per slide. Wit met zwarte outline = TikTok standaard.",
    cta:"Spark Ad link",
    why:"Beat-synced content = extended dwell time + replays = meer views per persoon. TikTok beloont authenticiteit boven productie. De Boom Clap trend is specifiek trending in maart 2026.",
    psychology:"Ritmische audio-visuele alignment voelt 'juist' — het brein zoekt patronen. Als visual cuts op beats landen, kijken mensen tot het einde. Satisfying = rewatch = meer views.",
    proof:[{brand:"Boom Clap trend",detail:"Trending NOW maart 2026. Charli XCX audio = algoritmische boost."},{brand:"Beat-sync data",detail:"Beat-synced content = hogere completion rate + replays."},{brand:"Text-based format",detail:"Tekst aanwezig = +58% recall, +11% purchase intent (TikTok data)."}],
    equipment:["5 sterke product/lifestyle foto's","CapCut of TikTok editor voor beat sync","Charli XCX 'Boom Clap' audio"],
    caption:"school fit",
    audio:"Charli XCX — 'Boom Clap' (TRENDING maart 2026)",
    firstSlide:"Striking outfit foto met bold tekst die op de eerste beat landt",
    backedBy:"Boom Clap trend (trending NOW), beat-sync psychology, +58% recall door tekst overlay",
    goal:"Views + replays. Dwell time maximaliseren.",
    imageRules:"Elke slide = sterke visual (product on body, detail, lifestyle). Tekst: bold, readable, 2-4 woorden. Wit + zwarte outline. TikTok Auto-Sync of CapCut beat markers voor timing.",
    steps:[
      {title:"Slide 1: Eerste Beat",action:"Beste outfit/product foto. Bold tekst die PRECIES op de eerste beat van Boom Clap landt. Bijv: '460 GSM'",camera:"Phone",angle:"Full outfit of striking detail",lighting:"Natuurlijk",duration:"",tip:"Eerste beat = eerste tekst = instant engagement."},
      {title:"Slide 2: Tweede Beat",action:"Andere hoek of detail. Tekst: 'Double stitched' of 'Built different'",camera:"Phone",angle:"Close-up of andere hoek",lighting:"Consistent met slide 1",duration:"",tip:"Houd de tekst kort — 2-4 woorden max."},
      {title:"Slide 3: Derde Beat",action:"Fabric detail of label. Tekst: 'Made with intention' of 'Not fast fashion'",camera:"Phone",angle:"Macro/detail",lighting:"Consistent",duration:"",tip:"Elk stukje tekst bouwt het verhaal op."},
      {title:"Slide 4: Vierde Beat",action:"Candid/movement shot. Tekst: 'Not another blank' of '€45'",camera:"Phone",angle:"Walking/candid",lighting:"Natuurlijk, outdoor of lifestyle",duration:"",tip:"Movement voegt energie toe."},
      {title:"Slide 5: Finale",action:"Beste lifestyle shot. Tekst: 'NEWGARMENTS' of je tagline.",camera:"Phone",angle:"Hero shot",lighting:"Best mogelijke",duration:"",tip:"Eindig sterk — dit is de save/screenshot slide."}
    ]
  },
  {
    id:"s3",title:"B&W Silhouette → Color Reveal",potential:94,difficulty:2,tags:["silhouette","aesthetic","reveal"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Zwarte silhouette — de oversized shape als ster",
    hookNote:"AI/CapCut silhouette filter. Focus op de SHAPE van de kleding. Oversized fit is de hoofdpersoon. Finale slide = color reveal. Dark aesthetic = streetwear taal.",
    textOverlay:"Minimaal — laat de silhouettes spreken. Optioneel: slide 5 tekst bij reveal.",
    cta:"Spark Ad link",
    why:"Silhouette valt op in kleurrijk FYP door pattern interruption. De shape-focus is PERFECT voor oversized streetwear. De color reveal op het einde = beloning voor swipen.",
    psychology:"Contrast = aandacht. Zwart op kleurrijke FYP = instant scroll-stop. De build-up naar de reveal creëert anticipatie. Satisfying reveal = saves.",
    proof:[{brand:"Silhouette trend",detail:"CapCut templates beschikbaar. Dark aesthetic = trending voor fashion."},{brand:"Pattern interruption",detail:"Stilstaand B&W beeld in kleurrijke FYP = automatische scroll-stop."},{brand:"Reveal format",detail:"Before/after en reveal = hoogste swipe-through rate."}],
    equipment:["4-5 outfit foto's (verschillende hoeken)","CapCut voor silhouette effect","Dark atmospheric audio"],
    caption:"you know the shape",
    audio:"Dark atmospheric beat of moody trending audio",
    firstSlide:"Zwarte silhouette van persoon in hoodie — oversized shape",
    backedBy:"Silhouette trend, pattern interruption psychologie, CapCut templates",
    goal:"Scroll-stop op FYP + reveal engagement.",
    imageRules:"Silhouettes: CapCut silhouette effect OF handmatig (exposure omlaag, contrast omhoog). Alle slides B&W/donker BEHALVE laatste = full color reveal. Consistente hoeken.",
    steps:[
      {title:"Slide 1: Silhouette Voorkant",action:"Zwarte silhouette — voorkant. Oversized shape, drop shoulders duidelijk zichtbaar.",camera:"Phone, backlit",angle:"Voorkant, full body",lighting:"Backlit voor silhouette of CapCut filter",duration:"",tip:"De shape moet HERKENBAAR zijn als een oversized hoodie."},
      {title:"Slide 2: Silhouette Zijkant",action:"Silhouette — zijkant. Hoodie lengte en boxy fit tonen.",camera:"Phone",angle:"Zijkant, full body",lighting:"Zelfde als slide 1",duration:"",tip:"Zijkant toont de drop en de lengte."},
      {title:"Slide 3: Silhouette Achterkant",action:"Silhouette — achterkant. Hood shape en back detail.",camera:"Phone",angle:"Achterkant",lighting:"Consistent",duration:"",tip:"3 hoeken = complete shape showcase."},
      {title:"Slide 4: Silhouette Beweging",action:"Walking silhouette of dynamische pose. Beweging voegt leven toe.",camera:"Phone",angle:"Walking/dynamisch",lighting:"Consistent",duration:"",tip:"Beweging in een stilstaand beeld = extra interessant."},
      {title:"Slide 5: COLOR REVEAL",action:"FULL COLOR — persoon in hoodie. Best mogelijke shot. De beloning voor het swipen.",camera:"Phone",angle:"Zelfde hoek als slide 1 (voor vergelijking)",lighting:"Warm, natuurlijk — contrast met de donkere silhouettes",duration:"",tip:"Dit is het moment. Maak het je beste foto."}
    ]
  },
  {
    id:"s4",title:"Twist-Ending Punchline",potential:93,difficulty:1,tags:["humor","meme","viral"],platforms:["TikTok Spark Ad"],duration:"3 slides",
    hook:"Relatable tekst + foto die de grap opzet",
    hookNote:"Meme setup → product als punchline. Humor disarmt ad resistance. Viewers MOETEN swipen voor de punchline. Product voelt als een grap, niet als een pitch.",
    textOverlay:"Bold tekst op elke slide. Meme-style formatting. Punchline = product reveal op laatste slide.",
    cta:"Spark Ad link",
    why:"Humor = native FYP content. Niemand verwacht een ad. De punchline forceert swipen. 20-30% hogere CTR voor carousel ads met storytelling. Product = punchline, niet pitch.",
    psychology:"Humor verlaagt de guard. Als mensen lachen, zijn ze open voor het product. De twist ending = dopamine hit. Ze delen het omdat het grappig is, niet omdat het een ad is.",
    proof:[{brand:"Carousel storytelling",detail:"20-30% hogere CTR, 18% langere view time bij storytelling sequence."},{brand:"Humor format",detail:"66% consumers prefereert native content over polished ads. Humor = meest native."},{brand:"Swipe-through",detail:"Twist ending forceert swipen — je MOET de punchline zien."}],
    equipment:["Phone camera","Creativiteit voor de grap","Product foto's"],
    caption:"every single time",
    audio:"Trending upbeat track of comedic audio",
    firstSlide:"Relatable tekst + foto die de grap opzet (NIET het product)",
    backedBy:"Meme carousel format, humor psychology, 20-30% hogere CTR bij storytelling",
    goal:"Virality + shares. Humor = meest deelbare content.",
    imageRules:"Foto's kunnen memes, staged shots, screenshots of lifestyle zijn. LAATSTE slide = product als punchline. Tekst bold en readable. Phone-shot aesthetic.",
    steps:[
      {title:"Slide 1: De Setup",action:"'Me saying I don't need another hoodie' — foto van kledingkast vol hoodies of jij die 'nee' zegt.",camera:"Phone",angle:"Casual, relatable",lighting:"Maakt niet uit — het gaat om de grap",duration:"",tip:"De setup moet HERKENBAAR zijn. Iedereen heeft dit gedacht."},
      {title:"Slide 2: De Build",action:"'The hoodie:' — screenshot van NEWGARMENTS website of product foto. Of: 'Also me: *adds to cart*'",camera:"Phone/screenshot",angle:"Product zichtbaar",lighting:"N/A",duration:"",tip:"Dit is de bridge — het verbindt de setup met de punchline."},
      {title:"Slide 3: De Punchline",action:"'Me 3 days later' — foto van jezelf blij met het pakket of in de hoodie. Of: 'No regrets'",camera:"Phone",angle:"Blij, casual, echt",lighting:"Natuurlijk",duration:"",tip:"De punchline IS het product moment. Het moet een glimlach opleveren."}
    ]
  },
  {
    id:"s5",title:"\"Hard Times\" Relatable Problems",potential:90,difficulty:1,tags:["humor","community","relatable"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Relatable probleem + relevante foto",
    hookNote:"Paramore 'Hard Times' — upbeat muziek + relatable struggles. Elke slide = een probleem dat je doelgroep herkent. Product = payoff op het einde. Community humor format.",
    textOverlay:"Elke slide: bold tekst met een relatable probleem. Upbeat font/style die matcht met de muziek energie.",
    cta:"Spark Ad link",
    why:"Iedereen herkent deze struggles. Upbeat muziek maakt het shareable. Product is de payoff, niet de pitch. Community building — comments vol 'me too'.",
    psychology:"Relatable humor = laagste ad resistance. Gedeeld leed = verbinding. De upbeat muziek contrasteert met de 'problemen' = grappig contrast. Comments = engagement signals.",
    proof:[{brand:"Paramore Hard Times",detail:"Trending sound op TikTok. Upbeat + negatief contrast = engagement trigger."},{brand:"Community humor",detail:"'Me too' comments = community building + algorithm fuel."},{brand:"Relatable content",detail:"66% prefereert native/friend content. Relatable struggles = meest native."}],
    equipment:["Phone camera","Screenshots/memes voor sommige slides","Product foto's voor reveal"],
    caption:"the struggle is real",
    audio:"Paramore — 'Hard Times'",
    firstSlide:"Tekst over een relatable probleem + relevante foto",
    backedBy:"Hard Times trending sound, community humor format, relatable content psychologie",
    goal:"Comments + shares. Community building.",
    imageRules:"Mix van memes, screenshots, staged shots en lifestyle. Energie upbeat om te matchen met de song. Laatste slide = product als payoff. Tekst bold en leesbaar.",
    steps:[
      {title:"Slide 1: Probleem 1",action:"'When you find the perfect hoodie but it's out of stock' — screenshot van 'sold out' pagina",camera:"Screenshot",angle:"N/A",lighting:"N/A",duration:"",tip:"Begin met het meest herkenbare probleem."},
      {title:"Slide 2: Probleem 2",action:"'When your friend buys the same one' — twee mensen in dezelfde outfit (kan staged zijn)",camera:"Phone",angle:"Twee mensen naast elkaar",lighting:"Casual",duration:"",tip:"Specifiek = grappiger dan vaag."},
      {title:"Slide 3: Probleem 3",action:"'When it's too warm but you wear it anyway' — persoon in hoodie in de zon",camera:"Phone",angle:"Outdoor, warm weer",lighting:"Zon/warm",duration:"",tip:"Dit is de relatable overwinning — iedereen doet dit."},
      {title:"Slide 4: Probleem 4",action:"'When fast fashion pills after 2 washes' — close-up van gepilde stof (niet jouw product)",camera:"Phone",angle:"Close-up detail",lighting:"N/A",duration:"",tip:"Dit zet de kwaliteits-payoff op."},
      {title:"Slide 5: De Payoff",action:"'When you find 460 GSM for €45' — JIJ blij in de NEWGARMENTS hoodie",camera:"Phone",angle:"Full outfit, blij gezicht",lighting:"Natuurlijk, goed licht",duration:"",tip:"De payoff is: JOUW product lost al deze problemen op."}
    ]
  },
  {
    id:"s6",title:"Birthday/Christmas Wishlist (Canva)",potential:96,difficulty:1,tags:["wishlist","saves","canva"],platforms:["TikTok Spark Ad"],duration:"6-7 slides",
    hook:"Title card: 'My 19th Birthday Wishlist'",
    hookNote:"Canva-designed wishlist. Magazine aesthetic. EXTREEM hoge save rate — mensen bookmarken als gift reference. #christmaswishlist = miljarden views. Jouw product staat NAAST Nike, Dior = premium positionering.",
    textOverlay:"Elke slide: product naam + prijs in aesthetic typografie. Clean layout.",
    cta:"Spark Ad link",
    why:"Iedereen maakt wishlists. Save rate uitzonderlijk hoog — mensen gebruiken het als shopping list. Je product naast premium merken = positionering. Canva templates beschikbaar.",
    psychology:"Wishlist = aspiratie. Het bookmarken is het begin van het koopproces. Door je product naast Nike en Dior te plaatsen, positioneer je het als premium. Social proof: 'als iemand dit op hun wishlist zet, moet het goed zijn.'",
    proof:[{brand:"#christmaswishlist",detail:"Miljarden views op TikTok. Canva wishlist = trending format."},{brand:"Save rate",detail:"Wishlist slideshows = hoogste save rate van alle carousel formats."},{brand:"40.3K+ likes",detail:"Individuele wishlist tutorial video's krijgen tienduizenden likes."}],
    equipment:["Canva account (gratis)","Product foto's","Foto's van andere wishlist items (Nike, parfum, tech)"],
    caption:"drop your wishlist below",
    audio:"Soft trending sound of lo-fi",
    firstSlide:"Title card: 'My 19th Birthday Wishlist' in aesthetic typografie",
    backedBy:"Wishlist trend (miljarden views), extreem hoge save rate, Canva templates",
    goal:"Saves. #1 doel. Mensen bookmarken als shopping list.",
    imageRules:"Canva-designed. Magazine/mood board aesthetic. Clean product images. Consistent kleurenpalet (donker/streetwear tones). 1-2 items per slide. NEWGARMENTS hoodie op slide 2 of 3 (prominent maar niet geforceerd).",
    steps:[
      {title:"Slide 1: Title Card",action:"'My 19th Birthday Wishlist' (pas leeftijd aan). Aesthetic typografie. Clean design. Geen product nog.",camera:"Canva design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"Canva → zoek 'birthday wishlist template' → 1080x1920."},
      {title:"Slide 2: NEWGARMENTS Hoodie",action:"Product foto + 'NEWGARMENTS 460 GSM Hoodie — €45'. Prominent maar niet de enige item.",camera:"Product foto",angle:"Clean shot",lighting:"Goed licht",duration:"5 min",tip:"Je product op slide 2 = prominent zonder geforceerd."},
      {title:"Slide 3: Trending Schoen",action:"Nike Dunk Low of trending schoen + naam + prijs.",camera:"Product foto (online)",angle:"N/A",lighting:"N/A",duration:"3 min",tip:"Naast Nike = premium positionering."},
      {title:"Slide 4: Parfum",action:"Trending parfum (Dior Sauvage, Bleu de Chanel) + prijs.",camera:"Product foto",angle:"N/A",lighting:"N/A",duration:"3 min",tip:"Diverse items = echte wishlist feel."},
      {title:"Slide 5: NEWGARMENTS #2",action:"Andere colorway van de hoodie. Of een 2e product.",camera:"Product foto",angle:"Clean",lighting:"Goed",duration:"3 min",tip:"2e NEWGARMENTS item voelt natuurlijk in een wishlist."},
      {title:"Slide 6: Tech Item",action:"AirPods, speaker, of trending tech + prijs.",camera:"Product foto",angle:"N/A",lighting:"N/A",duration:"3 min",tip:"Afwisseling houdt het geloofwaardig als echte wishlist."}
    ]
  },
  {
    id:"s7",title:"\"Sets With Me\" Product Flex (Rihanna)",potential:92,difficulty:2,tags:["product-showcase","trending","beat-sync"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Je best-verkopende of opvallendste colorway",
    hookNote:"Rihanna ANTI track — trending maart 2026. Product carousel, elke slide = ander product/colorway. Beat-synced transitions. Originated op NailTok, nu trending voor alle product showcases.",
    textOverlay:"'sets with me' op slide 1. Daarna geen tekst — laat producten spreken.",
    cta:"Spark Ad link",
    why:"Trending sound = discovery boost. Product showcase voelt als een flex, niet als een catalog. Beat-sync = visueel bevredigend. Rihanna audio = algoritmische boost.",
    psychology:"Confidence branding — je TOONT je lineup zonder het te verkopen. De viewer voelt de flex. Trending audio = FYP discovery. Beat-sync = satisfying loop.",
    proof:[{brand:"Sets With Me trend",detail:"Trending NOW maart 2026. Rihanna ANTI audio."},{brand:"NailTok origin",detail:"Originated als nail portfolio format → nu breed voor product showcases."},{brand:"Beat-sync",detail:"Beat-synced carousels = hogere completion rate + replays."}],
    equipment:["5-8 product foto's (verschillende colorways/pieces)","CapCut of TikTok editor voor beat sync","Rihanna ANTI track audio"],
    caption:"the lineup",
    audio:"Rihanna — ANTI album track (trending maart 2026)",
    firstSlide:"Best-verkopende of opvallendste product/colorway",
    backedBy:"Sets With Me trend (trending NOW), Rihanna audio = algoritmische boost",
    goal:"Product awareness + purchase consideration.",
    imageRules:"Clean product foto's OF styled on-body shots. Elke slide = ander product/colorway. Beat-synced transitions. Consistent editing style. Mix flat lays en on-body.",
    steps:[
      {title:"Slide 1: Hero Product",action:"Beste/meest opvallende colorway. Op persoon, best mogelijke shot. Tekst: 'sets with me'",camera:"Phone",angle:"Full outfit",lighting:"Goed, natuurlijk",duration:"",tip:"Dit is je scroll-stopper. Je sterkste stuk."},
      {title:"Slide 2: Tweede Colorway",action:"Andere kleur. Flat lay of op persoon.",camera:"Phone",angle:"Consistent met slide 1",lighting:"Consistent",duration:"",tip:"Variatie toont dat je meer hebt dan 1 product."},
      {title:"Slide 3: Detail Shot",action:"Close-up van fabric, label, of uniek detail.",camera:"Phone, dichtbij",angle:"Detail/macro",lighting:"Goed",duration:"",tip:"Kwaliteit bewijs zonder het te zeggen."},
      {title:"Slide 4: Lifestyle/On-Body",action:"Persoon in outfit, lifestyle setting.",camera:"Phone",angle:"Candid/lifestyle",lighting:"Natuurlijk",duration:"",tip:"Van product naar lifestyle — de transition matters."},
      {title:"Slide 5: Alle Colorways",action:"Group shot van alle producten samen. De collectie.",camera:"Phone",angle:"Flat lay of styled arrangement",lighting:"Clean, consistent",duration:"",tip:"De finale = 'hier is alles wat we hebben.'"}
    ]
  },
  {
    id:"s8",title:"Aesthetic Photo Dump + Product",potential:91,difficulty:1,tags:["photo-dump","native","lifestyle"],platforms:["TikTok Spark Ad"],duration:"8 slides",
    hook:"Lifestyle foto — NIET het product",
    hookNote:"Camera roll dump. Mix van koffie, architectuur, food, momenten — met product subtiel verweven. #photodump = 1.6 MILJARD views. Niet product-focused maar lifestyle met product erin.",
    textOverlay:"Geen tekst. Pure foto's. De aesthetic IS het verhaal.",
    cta:"Spark Ad link",
    why:"Dit IS hoe Gen Z content deelt. Product is er gewoon, niet gepitched. 1.6 miljard views op #photodump. Overly curated underperformt — raw dumps winnen. Native feel = 0 ad resistance.",
    psychology:"Photo dumps voelen als een friend's camera roll. Geen selling intent = geen ad resistance. Het product is gewoon onderdeel van iemand's leven. Dat is krachtiger dan elke pitch.",
    proof:[{brand:"#photodump",detail:"1.6 MILJARD views op TikTok. Gen Z's preferred sharing format."},{brand:"2.9x comments",detail:"Carousels krijgen 2.9x meer comments dan video."},{brand:"Raw > curated",detail:"Overly curated posts underperformen. Unfiltered dumps winnen."}],
    equipment:["Phone camera","Lifestyle momenten (koffie, straat, food, etc.)","Outfit foto's waar je hoodie casual zichtbaar is"],
    caption:"lately",
    audio:"Indie/lo-fi track of trending ambient",
    firstSlide:"Lifestyle foto — NIET het product. Koffie scene, warm licht, atmospheric moment.",
    backedBy:"#photodump (1.6B views), Gen Z preferred format, raw > curated data",
    goal:"Native engagement. Hoge save rate door aesthetic.",
    imageRules:"Phone-shot, film grain filter, warm tones. MIX van: close-up details, wide shots, food, textures, candid momenten, product verweven. Product in MAX 3 van 8 slides. Moet voelen als camera roll, niet lookbook.",
    steps:[
      {title:"Slide 1: Mood Setter",action:"Koffie/ontbijt scene of atmospheric moment. Warm licht. GEEN product.",camera:"Phone",angle:"Close-up of atmospheric",lighting:"Warm, natural",duration:"",tip:"Dit zet de mood. Product komt later."},
      {title:"Slide 2: Casual Product",action:"Candid van jezelf in hoodie, walking of casual moment.",camera:"Phone",angle:"Candid, niet posed",lighting:"Natural",duration:"",tip:"Het product is er gewoon. Niet gepitched."},
      {title:"Slide 3: Texture/Detail",action:"Architectuur, straat detail, of textuur. Geen product.",camera:"Phone",angle:"Creatief",lighting:"Varies",duration:"",tip:"Variatie houdt het interessant. Niet alles hoeft 'relevant' te zijn."},
      {title:"Slide 4: Subtiel Product",action:"Close-up van hoodie mouw terwijl je koffie vasthoudt, of detail terwijl je het draagt.",camera:"Phone",angle:"Detail, subtiel",lighting:"Warm",duration:"",tip:"Product is subtiel — mouw, label, fabric zichtbaar."},
      {title:"Slide 5: Life Moment",action:"Eten/restaurant moment of een ander life moment. Geen product.",camera:"Phone",angle:"Casual",lighting:"Varies",duration:"",tip:"Dit is wat de dump 'echt' maakt."},
      {title:"Slide 6: Spiegel Selfie",action:"Volledige outfit in spiegel. Product duidelijk zichtbaar.",camera:"Phone, spiegel",angle:"Full body spiegel",lighting:"Kamer licht",duration:"",tip:"De 'fit check' moment in de dump."},
      {title:"Slide 7: Nature/Skyline",action:"Sunset, skyline, park of natuur. Geen product.",camera:"Phone",angle:"Wide/atmospheric",lighting:"Golden hour ideal",duration:"",tip:"Eindig bijna op een mooi moment."},
      {title:"Slide 8: Social Proof",action:"Groepsfoto met vrienden. Jij draagt hoodie.",camera:"Phone",angle:"Groep, casual",lighting:"Varies",duration:"",tip:"Social proof = meerdere mensen. Jouw hoodie is onderdeel van de groep."}
    ]
  },
  {
    id:"s9",title:"\"More of This in 2026\" Mood Board",potential:89,difficulty:1,tags:["mood-board","saves","aesthetic"],platforms:["TikTok Spark Ad"],duration:"7 slides",
    hook:"Aspirational lifestyle image met 'More of this in 2026' tekst",
    hookNote:"Pinterest-style mood board op TikTok. Curated aesthetic, cohesive kleurenpalet. Aspirational imagery triggert saves. Product verweven in de mood.",
    textOverlay:"Slide 1: 'More of this in 2026'. Rest: geen tekst.",
    cta:"Spark Ad link",
    why:"Mensen saven dit als inspo board. Product wordt onderdeel van hun aspiratie. Crossover Pinterest audience. Save = #1 algorithm signal.",
    psychology:"Aspiratie = verlangen zonder selling intent. Door je product in een mood board te plaatsen, koppel je het aan een LEVENSSTIJL, niet aan specs. Mensen kopen levensstijlen, niet producten.",
    proof:[{brand:"Mood board format",detail:"Mood board slides = hoogste save rate van carousel formats."},{brand:"Pinterest crossover",detail:"Pinterest-energy op TikTok = crossover audience die saves drijft."},{brand:"Aspirational content",detail:"Aspirational imagery triggert saves zonder verkoop-intentie."}],
    equipment:["Curated lifestyle foto's","Product foto's verweven","Canva voor consistente filter/edit"],
    caption:"the vision",
    audio:"Soft ambient of lo-fi trending",
    firstSlide:"Warm, aspirational lifestyle image met 'More of this in 2026' tekst",
    backedBy:"Mood board format (hoogste saves), Pinterest crossover, aspirational psychology",
    goal:"Saves. Aspirational product positionering.",
    imageRules:"CURATED aesthetic. Mix van: lifestyle, city, product, textures, food, architectuur. Cohesive kleurenpalet op ALLE slides. Product in 2-3 slides. Zelfde filter op alles. Warm tones.",
    steps:[
      {title:"Slide 1: Titel",action:"Warm, aspirational lifestyle image. Tekst: 'More of this in 2026'. Geen product.",camera:"Phone of curated image",angle:"Atmospheric",lighting:"Warm",duration:"",tip:"Dit is de aspiratie — het leven dat je wilt."},
      {title:"Slide 2: Product Mood",action:"Hoodie outfit shot. Past in de mood, niet er bovenop.",camera:"Phone",angle:"Lifestyle",lighting:"Warm, consistent met slide 1",duration:"",tip:"Product = onderdeel van de mood, niet het onderwerp."},
      {title:"Slide 3: Cityscape",action:"Stad, architectuur, of straat detail. Aesthetic.",camera:"Phone",angle:"Creatief",lighting:"Consistent kleurenpalet",duration:"",tip:"Variatie, maar ZELFDE vibe."},
      {title:"Slide 4: Detail",action:"NEWGARMENTS detail — fabric, label. Subtiel.",camera:"Phone",angle:"Close-up",lighting:"Warm",duration:"",tip:"Kwaliteit als onderdeel van de aspiratie."},
      {title:"Slide 5: Connection",action:"Vrienden, casual moment. Social.",camera:"Phone",angle:"Candid",lighting:"Warm",duration:"",tip:"De mood board gaat over een heel leven, niet alleen kleding."},
      {title:"Slide 6: Creative",action:"Workspace, creatief moment, of hobby.",camera:"Phone",angle:"Varies",lighting:"Consistent",duration:"",tip:"Laat zien welk LEVEN bij het merk hoort."},
      {title:"Slide 7: Finale",action:"Beste outfit foto — NEWGARMENTS. De vision = complete.",camera:"Phone",angle:"Best shot",lighting:"Warm, mooi licht",duration:"",tip:"Eindig op het sterkste beeld. Dit is de save-slide."}
    ]
  },
  {
    id:"s10",title:"Quiet Flex / Lifestyle Carousel",potential:88,difficulty:1,tags:["lifestyle","understated","native"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Calm, aspirational lifestyle moment",
    hookNote:"2026 understated luxury trend. Geen specs, geen CTA, geen marketing. Puur lifestyle met product casual zichtbaar. 'iykyk' energy.",
    textOverlay:"GEEN tekst. Puur beeld. De foto's vertellen het verhaal.",
    cta:"Spark Ad link",
    why:"+72% purchase intent wanneer persoon product draagt. Lifestyle imagery = +40% conversie. UGC-style = +55% ROI. Het meest native format dat bestaat.",
    psychology:"'Stealth wealth' — niet opscheppen, gewoon leven. Het product is er gewoon. Geen verkoopintentie = geen weerstand. De viewer wil dit leven, niet dit product.",
    proof:[{brand:"TikTok data",detail:"+72% purchase intent bij persoon met product. +40% conversie lifestyle vs product-only."},{brand:"UGC ROI",detail:"UGC = +55% ROI vs non-UGC. Unbranded = +19% beter dan branded."},{brand:"Quiet luxury",detail:"2026 understated luxury = trending aesthetic."}],
    equipment:["Phone camera","Warme, cozy settings","Outfit foto's waar hoodie casual zichtbaar is"],
    caption:"iykyk",
    audio:"Lo-fi of ambient trending sound",
    firstSlide:"Calm, aspirational lifestyle — warm lighting, clean space. Persoon draagt hoodie casual.",
    backedBy:"+72% purchase intent (persoon + product), UGC +55% ROI, quiet luxury trend 2026",
    goal:"Purchase intent. Native conversie zonder te verkopen.",
    imageRules:"Warm, cozy lighting. Neutrale kleuren. Clean spaces. MINIMAAL. Product casual zichtbaar — gedragen terwijl koffie gemaakt wordt, op stoel gedrapeerd, zichtbaar terwijl je loopt. Geen product focus.",
    steps:[
      {title:"Slide 1: Morning Moment",action:"Koffie maken of ochtend moment. Draagt hoodie casual. Warm licht.",camera:"Phone",angle:"Lifestyle, niet posed",lighting:"Warm, ochtendlicht",duration:"",tip:"De calm vibe = scroll-stop op een drukke FYP."},
      {title:"Slide 2: In Movement",action:"Walking door de stad of in huis. Hoodie zichtbaar maar niet de focus.",camera:"Phone",angle:"Candid",lighting:"Natural",duration:"",tip:"Beweging = leven. Niet een photoshoot."},
      {title:"Slide 3: Detail Moment",action:"Handen om koffiekop, mouw zichtbaar. Of laptop werk, hoodie aan.",camera:"Phone",angle:"Close-up detail",lighting:"Warm",duration:"",tip:"De hoodie is er gewoon. Subtiel maar zichtbaar."},
      {title:"Slide 4: At Ease",action:"Lezen, relaxen, of creative moment. Hoodie als comfort piece.",camera:"Phone",angle:"Relaxed",lighting:"Warm, cozy",duration:"",tip:"Dit is het 'ik wil dit leven' moment."},
      {title:"Slide 5: Best Shot",action:"Outfit van de dag. Volledige look zichtbaar. Beste foto.",camera:"Phone",angle:"Full body, best angle",lighting:"Best mogelijke",duration:"",tip:"Eindig sterk. Dit is de screenshot/save slide."}
    ]
  },
  {
    id:"s11",title:"1 Hoodie, 7 Days (Weekly Outfits)",potential:98,difficulty:2,tags:["utility","saves","styling"],platforms:["TikTok Spark Ad"],duration:"7 slides",
    hook:"Maandag outfit — sterkste/cleanste look",
    hookNote:"7 slides = 7 dagen = 7 outfits, 1 hoodie. Bewijst veelzijdigheid. HOOGSTE save rate — mensen bookmarken voor outfit inspo. Gymshark: 50+ opeenvolgende carousels, 1 post = 5.6M views.",
    textOverlay:"Dag label op elke slide (Monday, Tuesday, etc.).",
    cta:"Spark Ad link",
    why:"Utility = saves. Styling carousels = #1 meest-gesaved format. 7 slides = hoge dwell time + veel swipes = algorithm signals. Bewijst dat je hoodie €45 waard is door veelzijdigheid. Gymshark bewezen.",
    psychology:"Praktisch nut = save reflex. Mensen bookmarken om outfits te kopiëren. De consistentie (zelfde spiegel, zelfde hoek) is visueel bevredigend. 7 variaties bewijzen waarde.",
    proof:[{brand:"Gymshark",detail:"5M+ followers, 50+ opeenvolgende photo carousels, 1 post = 5.6M views, 1.8% engagement rate."},{brand:"Styling carousels",detail:"#1 meest-gesaved carousel format op TikTok."},{brand:"Outfit of the week",detail:"Trending format met miljarden views."}],
    equipment:["1 NEWGARMENTS hoodie","7 complete outfits (broeken, schoenen, accessoires)","Zelfde spiegel/locatie voor alle 7 shots"],
    caption:"1 hoodie. 7 days.",
    audio:"Upbeat trending sound",
    firstSlide:"Maandag outfit — sterkste, cleanste look. Mirror selfie of friend-shot.",
    backedBy:"Gymshark (5.6M views per carousel), #1 meest-gesaved format, outfit-of-week trend",
    goal:"Saves. Veelzijdigheid bewijzen. Purchase consideration.",
    imageRules:"CONSISTENTIE is key: zelfde spiegel/locatie, zelfde hoek, zelfde lighting voor alle 7 slides. Alleen de outfit verandert. Elke outfit moet ECHT anders zijn — niet minieme variaties.",
    steps:[
      {title:"Slide 1: Monday",action:"Sterkste look. Hoodie + wide leg jeans + Air Force 1. Dag label: 'Monday'. Zet de standaard.",camera:"Phone, spiegel of vriend",angle:"Full body, ZELFDE hoek voor alle slides",lighting:"Consistent — dezelfde locatie",duration:"",tip:"Begin sterk. Dit is je scroll-stopper op de FYP."},
      {title:"Slide 2: Tuesday",action:"Hoodie + cargo pants + New Balance 550. Dag label: 'Tuesday'.",camera:"ZELFDE als slide 1",angle:"ZELFDE hoek",lighting:"ZELFDE locatie",duration:"",tip:"De consistentie is wat het bevredigend maakt om door te swipen."},
      {title:"Slide 3: Wednesday",action:"Hoodie + jogger + Dunk Low. Dag label: 'Wednesday'.",camera:"ZELFDE",angle:"ZELFDE",lighting:"ZELFDE",duration:"",tip:"Streetwear casual look."},
      {title:"Slide 4: Thursday",action:"Hoodie over overhemd + chinos + loafers. Dag label: 'Thursday'. Laat zien dat het dressy kan.",camera:"ZELFDE",angle:"ZELFDE",lighting:"ZELFDE",duration:"",tip:"Verrassing — de hoodie kan ook 'net' gestyled worden."},
      {title:"Slide 5: Friday",action:"Hoodie + shorts + slides. Casual Friday vibe. Dag label: 'Friday'.",camera:"ZELFDE",angle:"ZELFDE",lighting:"ZELFDE",duration:"",tip:"Relaxed maar nog steeds goed."},
      {title:"Slide 6: Saturday",action:"Hoodie + leren broek of jacket combo + boots. Going out look. Dag label: 'Saturday'.",camera:"ZELFDE",angle:"ZELFDE",lighting:"ZELFDE",duration:"",tip:"Weekend = bolder styling."},
      {title:"Slide 7: Sunday",action:"Hoodie + matching sweatpants. Full lounge mode. Dag label: 'Sunday'.",camera:"ZELFDE",angle:"ZELFDE",lighting:"ZELFDE",duration:"",tip:"Eindig op comfort. Dit is hoe mensen het echt dragen."}
    ]
  },
  {
    id:"s12",title:"Primadonna Girl 2-Slide Glow-Up",potential:90,difficulty:1,tags:["trending","before-after","brand-story"],platforms:["TikTok Spark Ad"],duration:"2 slides",
    hook:"Throwback/humble beginning foto",
    hookNote:"Marina 'Primadonna Girl' — trending NOW feb-maart 2026. 2 slides: before → after. Brand evolution of personal glow-up. 2 slides = 100% completion rate.",
    textOverlay:"Minimaal. Laat het contrast spreken. Optioneel: 'then' en 'now'.",
    cta:"Spark Ad link",
    why:"2 slides = snelste format. IEDEREEN compleet de carousel. Trending sound = discovery. Before/after contrast vertelt het verhaal zonder woorden. Brand evolution builds trust.",
    psychology:"Glow-up = universeel bevredigend. De contrast triggert een emotionele response. 'Van hier naar hier' = aspiratie. Mensen delen dit als inspiratie.",
    proof:[{brand:"Primadonna Girl trend",detail:"Trending NOW feb-maart 2026. Marina audio."},{brand:"2-slide format",detail:"Minimum slides = maximum completion rate. 100% ziet beide slides."},{brand:"Before/after",detail:"Reveal format = hoogste swipe-through rate van alle carousel types."}],
    equipment:["1 throwback/beginning foto","1 huidige/best mogelijke foto","Marina audio"],
    caption:"we always knew",
    audio:"Marina and the Diamonds — 'Primadonna Girl' (TRENDING)",
    firstSlide:"Throwback of humble beginning — raw, early, unperfect",
    backedBy:"Primadonna Girl trend (trending NOW), 100% completion rate, before/after psychology",
    goal:"Brand story + emotional connection. Trust building.",
    imageRules:"2 FOTO'S ALLEEN. Slide 1 = raw, early, humble. Slide 2 = polished, successful, arrived. Visuele continuïteit helpt (zelfde hoek, zelfde setting geëvolueerd).",
    steps:[
      {title:"Slide 1: The Beginning",action:"Allereerste NEWGARMENTS foto, prototype, eerste bestelling, of jij in een basic hoodie. Raw, unperfect, early days.",camera:"Oud/archief materiaal",angle:"Maakt niet uit — het moet 'vroeg' voelen",lighting:"Maakt niet uit",duration:"",tip:"Hoe 'slechter' slide 1 eruitziet, hoe krachtiger het contrast."},
      {title:"Slide 2: The Arrival",action:"Huidige product — best mogelijke shot. Persoon in hoodie, premium feel. Het 'arrived' moment.",camera:"Phone, best mogelijke shot",angle:"Best angle",lighting:"Best mogelijke licht",duration:"",tip:"Dit moet je BESTE foto zijn. Het hele punt is het contrast met slide 1."}
    ]
  },
  {
    id:"s13",title:"Sunshine Boy — Seasonal Transition",potential:87,difficulty:1,tags:["seasonal","trending","Rihanna"],platforms:["TikTok Spark Ad"],duration:"2-4 slides",
    hook:"Donkere winter scene, persoon in hoodie",
    hookNote:"Rihanna 'Kiss It Better' — trending NOW maart 2026. Winter vs zomer contrast. 'Been waiting on that sunshine boy...' Seizoens-transitie dat resoneert in maart.",
    textOverlay:"Slide 1: 'been waiting on that sunshine boy...' Overige slides: geen tekst.",
    cta:"Spark Ad link",
    why:"Iedereen in maart wacht op warmere dagen. Timing relevance = hogere engagement. Rihanna audio = algoritmische boost. Seizoens-content voelt relevant en native.",
    psychology:"Seizoens-nostalgie = universele emotie. In maart voelt iedereen de winter-moeheid. De transitie naar warmte = hoop. Je product als onderdeel van die transitie.",
    proof:[{brand:"Sunshine Boy trend",detail:"Trending NOW maart 2026. Rihanna 'Kiss It Better' audio."},{brand:"Seizoens-content",detail:"Timing relevance = hogere engagement dan evergreen content."},{brand:"Rihanna audio",detail:"Trending audio = algoritmische discovery boost."}],
    equipment:["Winter outfit foto's","Zomer/lente outfit foto's","Rihanna audio"],
    caption:"winter fit",
    audio:"Rihanna — 'Kiss It Better' (TRENDING maart 2026)",
    firstSlide:"Donkere winter scene — persoon in hoodie, regen of grijs weer",
    backedBy:"Sunshine Boy trend (trending NOW), seizoens-relevantie maart, Rihanna audio boost",
    goal:"Seasonal relevance + trending audio discovery.",
    imageRules:"2-4 slides. Slide 1 = winter/donker/koud. Laatste slide = warmte/lente/licht. Het contrast vertelt het verhaal. Hoodie als constante door beide seizoenen.",
    steps:[
      {title:"Slide 1: Winter",action:"Donkere winter scene. Regenachtig, grijs. Persoon in NEWGARMENTS hoodie. Tekst: 'been waiting on that sunshine boy...'",camera:"Phone",angle:"Atmospheric",lighting:"Donker, winter",duration:"",tip:"De winter-mood moet voelbaar zijn."},
      {title:"Slide 2: Sunshine",action:"Zelfde persoon, zomer/lente scene. Hoodie casual over schouders of lichtere styling. Warmte, zon.",camera:"Phone",angle:"Zelfde persoon, lichtere vibe",lighting:"Warm, zonnig",duration:"",tip:"Het contrast = de hele impact. Van donker naar licht."}
    ]
  },
  {
    id:"s14",title:"Gymshark-Style Fit Check Carousel",potential:93,difficulty:1,tags:["fit-check","native","proven"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Persoon in volledige outfit — mirror selfie of friend-shot",
    hookNote:"Gymshark: 5M+ followers, 50+ opeenvolgende photo carousels, 5.6M views op 1 post. Mix van product, on-body, detail, flat lay. Het BEWEZEN format.",
    textOverlay:"Geen of minimaal. De outfit spreekt.",
    cta:"Spark Ad link",
    why:"Als Gymshark 50+ opeenvolgende carousels post en 5.6M views haalt, werkt het. Simple execution, native feel, consistent posting. 1.8% engagement rate (extreem hoog voor brand).",
    psychology:"Fit check = meest native TikTok fashion format. Mirror selfie = hoe Gen Z daadwerkelijk mode deelt. Het bypassed ad detectie volledig. Voelt als een friend's post.",
    proof:[{brand:"Gymshark",detail:"5M followers, 50+ opeenvolgende carousels, 5.6M views op 1 post, 1.8% ER."},{brand:"Fit check format",detail:"Meest native TikTok fashion format. Miljarden views op #fitcheck."},{brand:"Person wearing",detail:"+72% purchase intent wanneer persoon product draagt (TikTok data)."}],
    equipment:["Volledige outfit","Spiegel of vriend met phone","Real setting"],
    caption:"fit check",
    audio:"Trending upbeat sound",
    firstSlide:"Persoon in volledige outfit. Mirror selfie of friend-shot. Hele look zichtbaar.",
    backedBy:"Gymshark (5.6M views, 50+ carousels), +72% purchase intent, #fitcheck miljarden views",
    goal:"Native engagement. Purchase intent door persoon + product.",
    imageRules:"Phone-shot. Real settings. Mix van: full outfit, detail close-up, andere hoek, flat lay, alt colorway. Geen studio. Geen perfectie. Native > polished.",
    steps:[
      {title:"Slide 1: Full Outfit",action:"Persoon in volledige outfit. Mirror selfie of friend-shot. Hele look van hoodie tot schoenen.",camera:"Phone",angle:"Full body",lighting:"Natuurlijk",duration:"",tip:"Dit is je FYP scroll-stopper. Moet eruitzien als een friend's post."},
      {title:"Slide 2: Detail Close-Up",action:"Fabric detail, label, stiksel. Kwaliteit zonder het te zeggen.",camera:"Phone, dichtbij",angle:"Macro/detail",lighting:"Goed licht op detail",duration:"",tip:"De dikte van 460 GSM is ZICHTBAAR. Laat het zien."},
      {title:"Slide 3: Andere Hoek",action:"Walking shot, candid, of achterkant. Movement of dynamiek.",camera:"Phone",angle:"Walking/candid/achterkant",lighting:"Natuurlijk",duration:"",tip:"Dezelfde outfit maar ander perspectief = meer informatie."},
      {title:"Slide 4: Flat Lay",action:"Hele outfit uitgelegd: hoodie + broek + schoenen + accessoires. Bird's eye view.",camera:"Phone, van boven",angle:"Bird's eye / flat lay",lighting:"Goed, gelijkmatig",duration:"",tip:"Dit is de 'shopping list' slide — saveable."},
      {title:"Slide 5: Alt Colorway of 2e Persoon",action:"Andere kleur hoodie of 2e persoon in dezelfde. Social proof + keuze.",camera:"Phone",angle:"Consistent met slide 1",lighting:"Consistent",duration:"",tip:"Opties = hogere purchase consideration."}
    ]
  },
  {
    id:"s15",title:"\"Rate This Fit\" Interactive",potential:91,difficulty:1,tags:["interactive","comments","engagement"],platforms:["TikTok Spark Ad"],duration:"3 slides",
    hook:"Outfit #1 met nummer label",
    hookNote:"Vraag-format = meeste comments. Elke slide = ander outfit. Caption vraagt om rating of keuze. Laagste drempel: iedereen typt een nummer. Elk comment = Spark Ad fuel.",
    textOverlay:"Nummer label op elke slide: '1', '2', '3'",
    cta:"Spark Ad link",
    why:"Carousels = 2.9x meer comments dan video. Vraag captions versterken dit. Elk comment = engagement signal. Voor Spark Ads: comments drijven de ad performance. Een nummer typen = 0 effort.",
    psychology:"Mensen kunnen niet NIET reageren op een simpele keuze. Het is te makkelijk. '1, 2, of 3' = drie opties = iedereen heeft een mening. Gamification = engagement.",
    proof:[{brand:"Carousel comments",detail:"2.9x meer comments dan video format."},{brand:"Vraag captions",detail:"Meeste comments van alle caption types."},{brand:"Spark Ads",detail:"Comments = engagement signal dat ad performance omhoog drijft."}],
    equipment:["3 complete outfits (zelfde hoodie, verschillende styling)","Phone camera","Consistent achtergrond"],
    caption:"which one? 1, 2, or 3?",
    audio:"Trending upbeat sound",
    firstSlide:"Outfit #1 met groot nummer '1' label. Sterkste look.",
    backedBy:"2.9x meer comments (carousel data), vraag captions = meeste comments, Spark Ad engagement fuel",
    goal:"Comments. Maximale engagement voor Spark Ad algorithm.",
    imageRules:"3 outfits, zelfde achtergrond, zelfde hoodie. Groot nummer label op elke slide. Consistent lighting en framing. Elke outfit moet duidelijk ANDERS zijn.",
    steps:[
      {title:"Slide 1: Outfit 1",action:"Zwarte hoodie + cargo + Dunks. Groot '1' label. Sterkste look.",camera:"Phone",angle:"Full body, consistent",lighting:"Consistent voor alle 3 slides",duration:"",tip:"Begin met je sterkste look om de scroll te stoppen."},
      {title:"Slide 2: Outfit 2",action:"Grijze hoodie + wide leg jeans + NB550. Groot '2' label.",camera:"ZELFDE positie",angle:"ZELFDE hoek",lighting:"ZELFDE",duration:"",tip:"De consistentie maakt de vergelijking makkelijk."},
      {title:"Slide 3: Outfit 3",action:"Witte hoodie + jogger + AF1. Groot '3' label.",camera:"ZELFDE",angle:"ZELFDE",lighting:"ZELFDE",duration:"",tip:"3 opties = iedereen kiest. Elk comment = algorithm fuel."}
    ]
  }
];
