const SLIDESHOW_IDEAS = [
  {
    id:"s1",title:"\"I Fw This\" Outfit Collage → Broke → Offer",potential:98,difficulty:1,tags:["conversion","PAS","own-proven"],platforms:["TikTok Spark Ad"],duration:"4 slides",
    hook:"Outfit collage + 'I fw this heavy 🔥'",
    hookNote:"BASED ON: Your own viral post (@newgarmentsclo/photo/7590800763165723937). Proven on YOUR account. Outfit collage → empty wallet → product offer → CTA. Complete PAS funnel in 4 slides.",
    textOverlay:"Slide 1: 'I fw this heavy 🔥' — Slide 2: 'but my bank account:' — Slide 3: 'Heavyweight Zipped Hoodie — 7 colors — €46.95' — Slide 4: 'Shop Now — upgrade your style without overpaying'",
    cta:"Shop Now via Spark Ad",
    why:"This is YOUR proven format that already works on your account. PAS (Problem-Agitate-Solve) is the #1 direct response framework. The broke slide is universally relatable, the offer solves it.",
    psychology:"'I fw this' = social validation. Empty wallet = shared pain. €46.95 after 'broke' context = feels like a solution. 4 slides = high completion rate.",
    proof:[{brand:"NEWGARMENTS own post",detail:"Proven format on @newgarmentsclo — outfit collage + PAS flow."},{brand:"PAS framework",detail:"#1 conversion framework in direct response advertising."}],
    equipment:["4 outfit photos wearing Heavyweight Zipped Hoodie (different colorways)","Empty wallet or €0 bank app screenshot","Product collage of all 7 colorways with prices","NEWGARMENTS logo on dark background"],
    caption:"the one 🤞",
    audio:"Trending lo-fi or soft beat",
    firstSlide:"2x2 collage: 4 outfits with Heavyweight Zipped Hoodie in Black, Navy, Purple, Red",
    backedBy:"Own proven post on @newgarmentsclo",
    sourceLinks:[{label:"YOUR OWN POST (this format)",url:"https://www.tiktok.com/@newgarmentsclo/photo/7590800763165723937"}],
    goal:"CONVERSION. Direct to shop. Proven on your account.",
    imageRules:"Slide 1 = 2x2 outfit collage (4 colorways). Slide 2 = empty wallet photo. Slide 3 = product grid with all colorways + prices. Slide 4 = logo + CTA on dark bg.",
    products:["Heavyweight Zipped Hoodie — Black (€46.95)","Heavyweight Zipped Hoodie — Navy Blue","Heavyweight Zipped Hoodie — Purple","Heavyweight Zipped Hoodie — Red"],
    steps:[
      {title:"Slide 1: Outfit Collage — 4 Colorways",action:"2x2 grid collage. Each photo = you wearing the Heavyweight Zipped Hoodie in a different color (Black, Navy, Purple, Red). Each styled differently. Text: 'I fw this heavy 🔥'",camera:"Phone — 4 separate outfit shots, combine in Canva",angle:"Mix: mirror selfie, friend-shot, candid, walking",lighting:"Natural, consistent",duration:"15 min",tip:"Use your 4 strongest colorways. Each outfit must look completely different."},
      {title:"Slide 2: The Problem — Broke",action:"Photo of empty wallet OR screenshot of bank app at €0.00. Text: 'but my bank account:'. Universal relatable moment.",camera:"Phone — close-up",angle:"Close-up of empty wallet",lighting:"Doesn't matter",duration:"2 min",tip:"The worse the 'broke' slide looks, the stronger the contrast with slide 3."},
      {title:"Slide 3: The Solution — Product Grid",action:"All 7 Heavyweight Zipped Hoodie colorways in a clean grid. Text: 'Heavyweight Zipped Hoodie — 7 colors — €46.95'. Price MUST be visible. Show: Black, Navy Blue, Purple, Red, Moss Green, Light-Gray, Pink.",camera:"Product photos arranged in Canva",angle:"Clean product grid",lighting:"Well-lit product shots",duration:"10 min",tip:"Price (€46.95) is the key. After the 'broke' slide, €46.95 feels affordable."},
      {title:"Slide 4: CTA — Shop Now",action:"NEWGARMENTS logo centered. Text: 'Shop Now — upgrade your style without overpaying'. Dark background, clean.",camera:"Canva design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"Clear, direct CTA. No ambiguity."}
    ]
  },
  {
    id:"s2",title:"\"Not Made For Everyone\" Exclusivity Drop",potential:97,difficulty:1,tags:["conversion","exclusivity","own-proven"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Dark moody hero shot + 'Not made for everyone'",
    hookNote:"BASED ON: Your own #1 post — 1.6M views, 10.1K likes, 2,725 saves. Caption: 'Not made for everyone... Free worldwide shipping'. Combined with Broken Planet's drop carousel format (@brokenplanet/photo/7544037377103219990). Exclusivity + scarcity = proven conversion driver.",
    textOverlay:"Slide 1: 'Not made for everyone.' — Slide 2: 'Heavyweight. Premium. Built to last.' — Slide 3: 'Distorted Knit — €41.95' — Slide 4: 'Once stock is gone, it's gone.' — Slide 5: 'Shop Now ⬇️ Free worldwide shipping'",
    cta:"Shop Now via Spark Ad",
    why:"Your #1 post ever (1.6M views) used this exact caption. Broken Planet uses the same scarcity model (limited drops, 1.3M views in 24 hours). Exclusivity + scarcity = the combination that moves streetwear.",
    psychology:"'Not made for everyone' = exclusivity (only for people with taste). Scarcity ('once it's gone') = FOMO. Free shipping removes the last objection. This is the Broken Planet / Corteiz playbook adapted for your brand.",
    proof:[{brand:"NEWGARMENTS #1 post",detail:"1.6M views, 10.1K likes, 2,725 saves — your best performing post EVER."},{brand:"Broken Planet",detail:"784K followers, 1.3M views in 24 hours on drop carousels. Photo carousel format confirmed."},{brand:"Corteiz",detail:"#1 streetwear brand 2025 (Complex). Same scarcity/exclusivity model."}],
    equipment:["'Distorted' Knit — moody dark photos","Detail/texture close-ups","On-body lifestyle shot","Logo + scarcity text + CTA"],
    caption:"not made for everyone.",
    audio:"Dark atmospheric beat",
    firstSlide:"Dark, moody hero shot of 'Distorted' Knit on person. Text: 'Not made for everyone.'",
    backedBy:"Your own #1 post (1.6M views), Broken Planet drop carousel format, Corteiz scarcity model",
    sourceLinks:[{label:"YOUR #1 POST (1.6M views)",url:"https://www.tiktok.com/@newgarmentsclo"},{label:"Broken Planet Drop Carousel",url:"https://www.tiktok.com/@brokenplanet/photo/7544037377103219990"}],
    goal:"CONVERSION via exclusivity + scarcity. 'Not for everyone' + 'once it's gone' = buy now.",
    imageRules:"Dark, moody aesthetic throughout. This is streetwear, not H&M. Low light, shadows, atmospheric. Product = the centerpiece. Scarcity text creates urgency.",
    products:["'Distorted' Knit (€41.95) — #1 Bestseller"],
    steps:[
      {title:"Slide 1: The Hook — 'Not Made For Everyone'",action:"Dark, moody shot of someone wearing the 'Distorted' Knit. Atmospheric lighting — shadows, low key. Text: 'Not made for everyone.' Bold, centered. This is your proven 1.6M view hook.",camera:"Phone — moody setting (dark room, backlit, street at night)",angle:"Full body or 3/4, showing the knit's texture",lighting:"Low key — backlighting or single lamp",duration:"",tip:"This exact caption got you 1.6M views. The dark mood + exclusivity text = proven scroll-stopper."},
      {title:"Slide 2: Product Details — Quality Flex",action:"Close-up of the 'Distorted' Knit texture, stitching, unique pattern. Text: 'Heavyweight. Premium. Built to last.' Let the quality speak without specs.",camera:"Phone — macro close-up",angle:"Fabric texture, pattern detail, label",lighting:"Good light on texture",duration:"",tip:"Show the unique distorted knit pattern up close. The texture IS the product."},
      {title:"Slide 3: Product + Price",action:"Full product shot — flat lay or on-body, clean. Text: 'Distorted Knit — €41.95'. Price visible, product name clear. This is the purchase slide.",camera:"Phone — clean product shot",angle:"Flat lay or styled on-body",lighting:"Clean, well-lit",duration:"",tip:"€41.95 is your #1 bestseller for a reason. The price point is right."},
      {title:"Slide 4: Scarcity — FOMO",action:"Dark background with bold text: 'Once stock is gone, it's gone.' or 'When stock runs out, our website closes.' This is the urgency trigger. Broken Planet does this every drop.",camera:"Canva — text on dark bg",angle:"N/A",lighting:"N/A",duration:"3 min",tip:"This mirrors your own bio ('WEBSITE WILL BE CLOSED ONCE SOLD OUT'). Use it."},
      {title:"Slide 5: CTA — Shop Now",action:"Logo + 'Shop Now ⬇️ Free worldwide shipping'. Free shipping removes the last objection after the scarcity trigger.",camera:"Canva design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"'Free worldwide shipping' was part of your 1.6M view caption. Keep it."}
    ]
  },
  {
    id:"s3",title:"Gymshark Reveal Carousel — \"Where Is This Going?\"",potential:95,difficulty:2,tags:["conversion","reveal","gymshark-format"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Mystery product shot — partial/hidden — 'You asked for heavyweight...'",
    hookNote:"BASED ON: Gymshark's reveal carousel format — 5.6M views on a single post. Their last 50 TikTok posts were ALL carousels. Format: slide 1 = mystery/tease, slides 2-4 = build anticipation, slide 5 = full reveal. Adapted for Heavyweight Zipped Hoodie.",
    textOverlay:"Slide 1: 'You asked for heavyweight...' — Slide 2: 'We delivered.' — Slide 3: '460 GSM. Double stitched. 7 colorways.' — Slide 4: (no text — let product speak) — Slide 5: 'Heavyweight Zipped Hoodie — €46.95 — Shop Now'",
    cta:"Shop Now via Spark Ad",
    why:"Gymshark posted 50+ consecutive carousels and one hit 5.6M views. Their 'Where Is This Going?' reveal format creates anticipation through swiping. The mystery hook forces swipes, and each swipe = algorithm signal.",
    psychology:"Curiosity gap: 'You asked for heavyweight...' → viewer MUST swipe to see what it is. Each reveal builds desire. By slide 5 they've invested 5 swipes = high purchase intent. Gymshark proved this at 5M+ follower scale.",
    proof:[{brand:"Gymshark",detail:"5.6M views on single carousel. Last 50 posts = ALL carousels. 6.5M followers, 133.3M total likes."},{brand:"Carousel reveal format",detail:"Reveal/surprise format creates anticipation through swiping. 20-30% higher CTR."}],
    equipment:["Heavyweight Zipped Hoodie — partial/hidden shots for tease","Detail close-ups for build-up","Full reveal hero shot","All 7 colorways for final spread"],
    caption:"you asked. we delivered.",
    audio:"Build-up/reveal trending sound",
    firstSlide:"Hoodie partially visible — fabric texture close-up or silhouette. Text: 'You asked for heavyweight...'",
    backedBy:"Gymshark (5.6M views per carousel, 50+ consecutive carousels, 6.5M followers)",
    sourceLinks:[{label:"Gymshark Carousel Strategy",url:"https://www.tiktok.com/@gymshark"},{label:"Gymshark Case Study",url:"https://www.milkkarten.net/p/tiktok-photo-mode-brands"}],
    goal:"CONVERSION via reveal curiosity. Each swipe builds desire → final slide = purchase.",
    imageRules:"Slide 1 = tease (partial, hidden, silhouette). Slides 2-3 = progressively reveal more. Slide 4 = full reveal. Slide 5 = purchase CTA. Build anticipation through the sequence.",
    products:["Heavyweight Zipped Hoodie — all 7 colorways (€46.95)"],
    steps:[
      {title:"Slide 1: The Tease — Partial Reveal",action:"Close-up of the fabric texture or zipper detail ONLY. Or silhouette of the hoodie. Don't show the full product yet. Text: 'You asked for heavyweight...' This creates the curiosity gap.",camera:"Phone — extreme close-up",angle:"Fabric texture only, or silhouette backlit",lighting:"Moody, atmospheric",duration:"",tip:"Gymshark's 5.6M view post used this exact reveal structure. The tease forces the swipe."},
      {title:"Slide 2: The Build — More Detail",action:"Show slightly more: the zipper, the hood shape, the drop shoulder. Still not the full product. Text: 'We delivered.' Building anticipation.",camera:"Phone — partial product",angle:"Detail shots — zipper, hood, shoulder",lighting:"Good detail lighting",duration:"",tip:"Each slide reveals a bit more. Like unwrapping a gift one layer at a time."},
      {title:"Slide 3: The Specs — Quality Proof",action:"Close-up collage: thick fabric cross-section, double stitching, premium label. Text: '460 GSM. Double stitched. 7 colorways.' Now they know WHAT it is but haven't seen the full thing yet.",camera:"Phone — macro details",angle:"Detail collage",lighting:"Well-lit",duration:"",tip:"The specs build the value BEFORE the full reveal. By the time they see it, they already want it."},
      {title:"Slide 4: The Full Reveal — Hero Shot",action:"FULL product reveal: person wearing the Heavyweight Zipped Hoodie, best possible shot. No text — let the product speak. This is the payoff for 3 slides of anticipation.",camera:"Phone — best possible shot",angle:"Full outfit, styled, fire",lighting:"Natural, warm, perfect",duration:"",tip:"This slide must be your absolute BEST photo. 3 slides of build-up lead to this moment."},
      {title:"Slide 5: CTA — All Colors + Purchase",action:"All 7 colorways laid out or in grid. Text: 'Heavyweight Zipped Hoodie — €46.95 — Shop Now ⬇️'. After the reveal, the viewer is ready to buy.",camera:"Product grid or flat lay of all colors",angle:"All 7 colorways visible",lighting:"Clean, even",duration:"",tip:"Showing all 7 colors = 'there's one for you'. Price after the reveal = no-brainer."}
    ]
  },
  {
    id:"s4",title:"White Fox \"Spotted\" Social Proof Format",potential:94,difficulty:2,tags:["conversion","social-proof","spotted"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Candid street photo + 'Spotted wearing NEWGARMENTS'",
    hookNote:"BASED ON: White Fox Boutique's 'Spotted in LA' format — $2.9M EMV from hoodie campaign alone. 1.5M followers. Format: show real people spotted wearing the product in the wild = massive social proof. Adapted for your Checkered Inside Out Zipper.",
    textOverlay:"Slide 1: 'Spotted 📸' — Slide 2: 'The Checkered Inside Out Zipper' — Slide 3: 'The hoodie everyone keeps asking about' — Slide 4: '€43.95 — 3 colors available' — Slide 5: 'Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"White Fox's 'Spotted in LA' hoodie post drove $2.9M in earned media. The 'spotted' format = street-level social proof. It implies people are wearing your product IRL = others must want it too. Strongest social proof format on TikTok.",
    psychology:"'Spotted' implies organic popularity (people are wearing it without being asked). Street photography feel = authentic, not staged. Other people's validation > brand's own claims. The viewer thinks: 'if they're wearing it, I should too.'",
    proof:[{brand:"White Fox Boutique",detail:"'Spotted in LA' hoodie campaign = $2.9M EMV. 305 posts. 1.5M followers."},{brand:"White Fox viral hoodie",detail:"Hoodie campaign URL: tiktok.com/@whitefox/video/7415546991595359496 — 'Shop the viral hoodie'"}],
    equipment:["Candid-style street photos of people wearing Checkered Inside Out Zipper","Detail close-ups of the checkered pattern","All 3 colorways (Gray, Black, Red)","Logo + CTA"],
    caption:"spotted 📸",
    audio:"Cool street/lifestyle trending sound",
    firstSlide:"Candid street-style photo of someone wearing Checkered Inside Out Zipper. Text: 'Spotted 📸'",
    backedBy:"White Fox 'Spotted in LA' format ($2.9M EMV), street photography social proof",
    sourceLinks:[{label:"White Fox 'Spotted' Viral Hoodie",url:"https://www.tiktok.com/@whitefox/video/7415546991595359496"},{label:"White Fox Lounge Hoodie",url:"https://www.tiktok.com/@whitefox/video/7490926433175391493"},{label:"White Fox Case Study",url:"https://www.creatoriq.com/blog/white-fox-boutique-top-apparel-brand-influencer-marketing"}],
    goal:"CONVERSION via 'spotted' social proof. If others are wearing it → I need it.",
    imageRules:"Street photography style — candid, not posed. Multiple people wearing the product in different settings. Must feel like REAL sightings, not a photoshoot. Raw, authentic, real.",
    products:["Checkered Inside Out Zipper — Gray (€43.95)","Checkered Inside Out Zipper — Black","Checkered Inside Out Zipper — Red"],
    steps:[
      {title:"Slide 1: Spotted — Street Candid",action:"Candid-style street photo of someone wearing the Checkered Inside Out Zipper. Text: 'Spotted 📸'. Must look like you saw someone wearing it and snapped a photo. White Fox style.",camera:"Phone — candid/street photography style",angle:"Slightly distance, street setting, natural",lighting:"Natural daylight, outdoor",duration:"",tip:"This must feel REAL, like a street photographer caught someone wearing it. Not a posed brand photo."},
      {title:"Slide 2: Product Reveal",action:"Clean shot of the Checkered Inside Out Zipper — showing the unique checkered pattern and inside-out design. Text: 'The Checkered Inside Out Zipper'. Product name reveal.",camera:"Phone — product detail",angle:"Show the checkered pattern clearly",lighting:"Good, detailed",duration:"",tip:"The unique checkered pattern is the differentiator. Make it the star."},
      {title:"Slide 3: Social Proof Text",action:"Another 'spotted' photo or on-body shot. Text: 'The hoodie everyone keeps asking about'. This reinforces that it's POPULAR — people are talking about it.",camera:"Phone — another street/lifestyle shot",angle:"Different person or different setting",lighting:"Natural",duration:"",tip:"Multiple sightings = more social proof. White Fox showed multiple people in LA wearing the hoodie."},
      {title:"Slide 4: All Colors + Price",action:"All 3 colorways (Gray, Black, Red) side by side. Text: '€43.95 — 3 colors available'. Price + options = purchase consideration.",camera:"Flat lay or product grid",angle:"All 3 colors visible",lighting:"Clean, even",duration:"",tip:"3 colors = choice. Price after social proof = easy decision."},
      {title:"Slide 5: CTA",action:"Logo + 'Shop Now ⬇️'. Clean, direct.",camera:"Canva design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"After 'spotted' social proof + all colors + price, the CTA closes the deal."}
    ]
  },
  {
    id:"s5",title:"COMFRT UGC Review — \"TikTok Made Me Buy This\"",potential:93,difficulty:1,tags:["conversion","UGC","review"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Unboxing NEWGARMENTS package + 'The hoodie TikTok made me buy'",
    hookNote:"BASED ON: COMFRT's UGC model — $23.31M in TikTok Shop sales, 520K+ units sold. 99.27% of sales from influencer/UGC content. Format: real person reviewing product, authentic feel. UGC = +55% ROI. Adapted for Heavyweight Zipped Hoodie.",
    textOverlay:"Slide 1: 'The hoodie TikTok made me buy' — Slide 2: 'This thickness is insane 😳' — Slide 3: 'The fit tho' — Slide 4: 'Double stitched. Built different.' — Slide 5: '€46.95 — worth every cent — Shop Now'",
    cta:"Shop Now via Spark Ad",
    why:"COMFRT made $23.31M selling hoodies through UGC reviews on TikTok. 99.27% came from creators, not brand content. The 'TikTok made me buy it' frame (72.5B views on the hashtag) is the most powerful commerce format. Your hoodie is perfect for this.",
    psychology:"Third-party validation > brand claims. 'TikTok made me buy it' implies thousands already bought it. Unboxing creates anticipation. Each slide = another proof point. By slide 5, the viewer is convinced.",
    proof:[{brand:"COMFRT",detail:"$23.31M TikTok Shop sales. 520K units. 99.27% from UGC/influencer content. Hoodie brand."},{brand:"#tiktokmademebuyit",detail:"72.5 BILLION views. Most powerful commerce hashtag."}],
    equipment:["NEWGARMENTS package (branded box/bag)","Heavyweight Zipped Hoodie for unboxing","On-body photos","Detail close-ups of fabric, stitching"],
    caption:"no cap this is insane",
    audio:"Trending reaction/review sound",
    firstSlide:"Hands opening NEWGARMENTS package. Text: 'The hoodie TikTok made me buy'",
    backedBy:"COMFRT ($23.31M from hoodie UGC), #tiktokmademebuyit (72.5B views)",
    sourceLinks:[{label:"COMFRT TikTok ($23.31M sales)",url:"https://www.tiktok.com/@comfrt"},{label:"COMFRT Case Study",url:"https://www.kalodata.com/blog/how-comfrt-brand-achieved-23-31m-in-tiktok-shop-sales"}],
    goal:"CONVERSION via UGC review. Feels like a real person recommending, not an ad.",
    imageRules:"ALL photos must look customer-made, not brand-made. Phone camera, casual setting, imperfect lighting. The imperfection IS the authenticity. No studio, no professional editing.",
    products:["Heavyweight Zipped Hoodie — Black (€46.95)"],
    steps:[
      {title:"Slide 1: Unboxing",action:"Hands opening the NEWGARMENTS package. Show branded packaging. Text: 'The hoodie TikTok made me buy'. Must look like a real customer, not a brand shoot.",camera:"Phone — POV/top-down",angle:"Hands + package",lighting:"Room light — casual",duration:"",tip:"COMFRT's entire $23.31M came from content like this. Authentic > polished."},
      {title:"Slide 2: First Impression — Thickness",action:"Holding the hoodie, squeezing the fabric to show thickness. Text: 'This thickness is insane 😳'. The 460 GSM weight is VISIBLE when you hold it.",camera:"Phone",angle:"Holding hoodie, showing weight/thickness",lighting:"Casual",duration:"",tip:"Squeeze the fabric. Let it spring back. 460 GSM is visually thick. This sells itself."},
      {title:"Slide 3: On-Body — The Fit",action:"Mirror selfie or friend-shot wearing the Heavyweight Zipped Hoodie. Full outfit. Text: 'The fit tho'. Show the boxy, oversized fit.",camera:"Phone — mirror selfie",angle:"Full body",lighting:"Natural",duration:"",tip:"The fit is the 2nd selling point after thickness. Boxy oversized = what they want."},
      {title:"Slide 4: Quality Details",action:"Close-up of double stitching, premium zipper, label. Text: 'Double stitched. Built different.' Quality proof.",camera:"Phone — close-up",angle:"Macro details — stitching, zipper, label",lighting:"Good light",duration:"",tip:"Details that a brand wouldn't normally show = this feels like an honest review."},
      {title:"Slide 5: Verdict + CTA",action:"Another shot wearing it + text: '€46.95 — worth every cent — Shop Now ⬇️'. Positive verdict with price and CTA.",camera:"Phone",angle:"Lifestyle",lighting:"Good",duration:"",tip:"'Worth every cent' is a verdict, not a sales pitch. After 4 proof slides, it's credible."}
    ]
  },
  {
    id:"s6",title:"PacSun Micro-Creator Simple Try-On",potential:92,difficulty:1,tags:["conversion","try-on","micro-creator"],platforms:["TikTok Spark Ad"],duration:"4 slides",
    hook:"Just received package + pulling product out",
    hookNote:"BASED ON: PacSun's viral moment — 11,000 jeans sold in 48 hours from a 5K-follower creator. Simple try-on format. No fancy editing. The raw simplicity IS the selling point. Adapted for Denim Striped Barrel Jeans (your #3 bestseller).",
    textOverlay:"Slide 1: 'Just got these in 📦' — Slide 2: 'Denim Striped Barrel Jeans' — Slide 3: 'The fit is actually insane' — Slide 4: '€34.95 — need these — Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"PacSun sold 11,000 pairs in 48 hours from ONE simple try-on post by a creator with only 5,000 followers. No fancy editing, no special effects. Just: here are the jeans, here's how they fit, link to buy. Your Barrel Jeans at €34.95 are in the impulse purchase sweet spot.",
    psychology:"Simplicity = authenticity. A raw try-on from a small creator feels more trustworthy than a brand campaign. €34.95 = impulse purchase range ($20-30 USD). Low price + authentic review = minimal purchase resistance.",
    proof:[{brand:"PacSun",detail:"11,000 jeans sold in 48 hours. Creator had only 5,000 followers. Simple try-on format."},{brand:"PacSun annual",detail:"$20M+ TikTok revenue. TikTok = 10% of e-commerce. 100K+ total pairs sold."}],
    equipment:["NEWGARMENTS package with Denim Striped Barrel Jeans inside","Try-on photos (before/after putting them on)","Full outfit shot","Close-up of striped denim detail"],
    caption:"these go crazy 🔥",
    audio:"Casual trending sound",
    firstSlide:"Hands pulling Denim Striped Barrel Jeans out of package. Text: 'Just got these in 📦'",
    backedBy:"PacSun (11K jeans sold in 48h from 5K-follower creator), impulse purchase price point",
    sourceLinks:[{label:"PacSun Viral Jeans Post",url:"https://www.tiktok.com/@pacsun/video/7443911815593069866"},{label:"PacSun Case Study (Digiday)",url:"https://digiday.com/marketing/how-fashion-retailer-pacsuns-viral-jeans-moment-on-tiktok-is-part-of-its-bigger-bet-on-creators/"}],
    goal:"CONVERSION via simple try-on. Raw authenticity + impulse price point = instant buy.",
    imageRules:"Maximum simplicity. Phone camera, bedroom/bathroom mirror, no editing. The rawness IS the credibility. If it looks too polished, it looks like an ad.",
    products:["Denim Striped Barrel Jeans — Blue (€34.95)","Denim Striped Barrel Jeans — Black (€34.95)"],
    steps:[
      {title:"Slide 1: Unboxing — Just Arrived",action:"Pulling Denim Striped Barrel Jeans out of the NEWGARMENTS package. Text: 'Just got these in 📦'. Raw, excited, authentic.",camera:"Phone — POV",angle:"Hands pulling product from package",lighting:"Room light",duration:"",tip:"PacSun's 11K pair viral moment came from content THIS simple. Don't overthink it."},
      {title:"Slide 2: The Product — Close-Up",action:"Holding the jeans up, showing the striped denim detail. Text: 'Denim Striped Barrel Jeans'. The unique stripe pattern is the hook.",camera:"Phone",angle:"Holding up, showing pattern",lighting:"Natural",duration:"",tip:"The striped barrel shape is unique. Show what makes them different from regular jeans."},
      {title:"Slide 3: Try-On — The Fit",action:"Full outfit with the jeans on. Mirror selfie or friend-shot. Text: 'The fit is actually insane'. Show the barrel/wide leg shape.",camera:"Phone — mirror",angle:"Full body, showing the full silhouette",lighting:"Natural",duration:"",tip:"The barrel fit is the selling point. Make sure the shape is clearly visible."},
      {title:"Slide 4: CTA — Price + Buy",action:"Another angle or both colorways (Blue + Black). Text: '€34.95 — need these — Shop Now ⬇️'. Impulse price + CTA.",camera:"Phone or Canva",angle:"Both colors if possible",lighting:"Good",duration:"",tip:"€34.95 is impulse range. After seeing the fit, price seals the deal."}
    ]
  },
  {
    id:"s7",title:"Odd Muse Founder Value Comparison",potential:91,difficulty:1,tags:["conversion","founder","comparison"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Side-by-side: competitor vs yours + 'Let me show you what €42 gets you'",
    hookNote:"BASED ON: Odd Muse founder Aimee Smale's comparison posts — scaled to £5M/year revenue. She compares her blazer's value vs competitors directly on camera. Founder-led content = highest trust. Adapted for 'Distorted' Knit vs competitor knits.",
    textOverlay:"Slide 1: 'Let me show you what €41.95 gets you' — Slide 2: 'Other brands: thin, basic knit — €60+' — Slide 3: 'NEWGARMENTS: Distorted Knit — €41.95' — Slide 4: 'Heavyweight. Unique pattern. Premium quality.' — Slide 5: 'Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Odd Muse went from zero to £5M/year using founder-led comparison content. When the FOUNDER shows you why their product is better value, it's more credible than any ad. Your 'Distorted' Knit at €41.95 vs competitor knits at €60+ = clear value win.",
    psychology:"Founder authority: when the person behind the brand makes the comparison, it carries weight. Price anchoring: show €60+ first, then €41.95. Side-by-side evidence = objective, not opinion.",
    proof:[{brand:"Odd Muse",detail:"£5M/year revenue from founder-led TikTok content. Blazer comparison posts went viral."},{brand:"Odd Muse founder",detail:"tiktok.com/@aimeesmalex/video/7424078027874700577 — founder comparing blazer value directly."}],
    equipment:["Competitor knit (or generic thin knit for comparison)","'Distorted' Knit","Side-by-side comparison photos","Price comparison graphic"],
    caption:"know your worth",
    audio:"Confident/flex trending sound",
    firstSlide:"Side-by-side: thin competitor knit (€60+) vs 'Distorted' Knit. Text: 'Let me show you what €41.95 gets you'",
    backedBy:"Odd Muse (£5M/year from founder comparison content), price anchoring psychology",
    sourceLinks:[{label:"Odd Muse Founder Comparison",url:"https://www.tiktok.com/@aimeesmalex/video/7424078027874700577"},{label:"Odd Muse Case Study",url:"https://www.tacticone.co/blog/odd-muse-founder-led-product-first-strategy"}],
    goal:"CONVERSION via founder-led value comparison. Show don't tell.",
    imageRules:"Side-by-side comparison must be OBVIOUS. Competitor = thin, basic, overpriced. Yours = premium, unique, better price. The visual difference must slap.",
    products:["'Distorted' Knit (€41.95) — #1 Bestseller"],
    steps:[
      {title:"Slide 1: The Comparison Setup",action:"Side-by-side: hold a thin/basic competitor knit next to your 'Distorted' Knit. Text: 'Let me show you what €41.95 gets you'. The difference in thickness/quality should be VISIBLE.",camera:"Phone — holding both products",angle:"Side-by-side, both clearly visible",lighting:"Good, even",duration:"",tip:"Odd Muse built £5M/year doing exactly this. The founder showing the comparison = maximum credibility."},
      {title:"Slide 2: The Competitor — Overpriced",action:"Close-up of the competitor/basic knit. Thin, basic, nothing special. Text: 'Other brands: thin, basic knit — €60+'. Show how underwhelming it is.",camera:"Phone — close-up",angle:"Detail showing thinness/basicness",lighting:"Normal",duration:"",tip:"Make the competitor look as basic as possible. The contrast with slide 3 does the selling."},
      {title:"Slide 3: Your Product — Better Value",action:"Close-up of 'Distorted' Knit. Thick, unique pattern, premium feel. Text: 'NEWGARMENTS: Distorted Knit — €41.95'. The upgrade is visual.",camera:"Phone — close-up",angle:"Detail showing unique pattern and thickness",lighting:"Good, warm",duration:"",tip:"The distorted knit pattern is unique. No competitor has this. That's your advantage."},
      {title:"Slide 4: On-Body — The Proof",action:"Person wearing the 'Distorted' Knit, looking fire. Text: 'Heavyweight. Unique pattern. Premium quality.' Let them see how it looks IRL.",camera:"Phone — friend-shot or mirror",angle:"Full outfit",lighting:"Natural, good",duration:"",tip:"After the comparison, seeing it on a real person seals the deal."},
      {title:"Slide 5: CTA",action:"Logo + 'Shop Now ⬇️' + €41.95. After the comparison, this is a no-brainer.",camera:"Canva design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"The math does itself: better product, lower price. CTA = easy decision."}
    ]
  },
  {
    id:"s8",title:"Full Outfit Combo — Hoodie + Jeans Styled",potential:96,difficulty:1,tags:["conversion","outfit","combo-deal"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Complete outfit flat lay + 'Full fit under €85'",
    hookNote:"BASED ON: Ralph Lauren's flat-lay showcase (@rachellliang — 20.9K likes) + Gymshark's outfit carousel format. Flat lay of COMPLETE outfit drives higher purchase consideration than single product. Combo deal = higher AOV. Uses your top 2 products together.",
    textOverlay:"Slide 1: 'Full fit under €85' — Slide 2: 'Heavyweight Zipped Hoodie — €46.95' — Slide 3: 'Denim Striped Barrel Jeans — €34.95' — Slide 4: 'Total: €81.90 + BUY 2 GET 30% OFF' — Slide 5: 'Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Flat-lay outfit combos are the most-saved carousel format. By showing hoodie + jeans together, you increase average order value. Your BUY 2 GET 30% OFF deal makes this even stronger — €81.90 becomes ~€57. Full outfit for under €60 = killer value proposition.",
    psychology:"Complete outfit = viewer can imagine wearing the full look (not just one piece). Budget framing ('under €85') removes price objection. Discount stacking ('BUY 2 GET 30% OFF') creates urgency and perceived value. Saves = algorithm boost.",
    proof:[{brand:"Ralph Lauren flat-lay",detail:"@rachellliang carousel — 20.9K likes, 71 comments. Flat-lay showcase = high engagement."},{brand:"Outfit combos",detail:"Complete outfit posts = most-saved carousel format on TikTok. Higher AOV than single product."}],
    equipment:["Heavyweight Zipped Hoodie — laid out","Denim Striped Barrel Jeans — laid out","Sneakers/accessories for complete look","On-body photo of full outfit"],
    caption:"the combo 🤝",
    audio:"Clean trending sound",
    firstSlide:"Bird's eye flat lay: Heavyweight Zipped Hoodie + Denim Striped Barrel Jeans + sneakers. Text: 'Full fit under €85'",
    backedBy:"Ralph Lauren flat-lay format (20.9K likes), outfit combo = highest save rate, BUY 2 GET 30% OFF",
    sourceLinks:[{label:"Ralph Lauren Flat-Lay Carousel",url:"https://www.tiktok.com/@rachellliang"},{label:"Gymshark Outfit Carousels",url:"https://www.tiktok.com/@gymshark"}],
    goal:"CONVERSION + higher AOV. Full outfit combo + discount = multiple items per order.",
    imageRules:"Slide 1 = bird's eye flat lay of complete outfit. Slides 2-3 = individual products with prices. Slide 4 = total + discount. Slide 5 = CTA. Clean, Pinterest-style aesthetic throughout.",
    products:["Heavyweight Zipped Hoodie — Black (€46.95)","Denim Striped Barrel Jeans — Blue (€34.95)"],
    steps:[
      {title:"Slide 1: Full Outfit Flat Lay",action:"Bird's eye view: Heavyweight Zipped Hoodie + Denim Striped Barrel Jeans + sneakers + accessories, all laid out clean. Text: 'Full fit under €85'. The complete look in one shot.",camera:"Phone — directly from above",angle:"Bird's eye / flat lay",lighting:"Clean, even, bright",duration:"10 min",tip:"Style it like a magazine spread. Each piece placed intentionally. Add sneakers + accessories for completeness."},
      {title:"Slide 2: Product 1 — Hoodie",action:"Heavyweight Zipped Hoodie solo or on-body. Text: 'Heavyweight Zipped Hoodie — €46.95'. Individual product + price.",camera:"Phone — product or on-body",angle:"Clean product shot",lighting:"Good",duration:"",tip:"Show it individually so the viewer registers each product and its price."},
      {title:"Slide 3: Product 2 — Jeans",action:"Denim Striped Barrel Jeans solo or on-body. Text: 'Denim Striped Barrel Jeans — €34.95'. The second product + price.",camera:"Phone — product or on-body",angle:"Show the striped detail + barrel shape",lighting:"Good",duration:"",tip:"Your #3 bestseller at €34.95. The unique stripe pattern is the differentiator."},
      {title:"Slide 4: Combo Deal — Discount Stack",action:"Both products together + text: 'Total: €81.90 + BUY 2 GET 30% OFF = ~€57'. The discount makes it irresistible. Full premium outfit for under €60.",camera:"Canva graphic or both products together",angle:"Both visible",lighting:"Clean",duration:"5 min",tip:"€57 for a full outfit = the headline. BUY 2 GET 30% OFF is your existing deal — use it."},
      {title:"Slide 5: CTA — Shop the Look",action:"Logo + 'Shop the full fit ⬇️'. Direct, specific CTA.",camera:"Canva design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"'Shop the full fit' = specific CTA that drives multi-product orders = higher AOV."}
    ]
  },
  {
    id:"s9",title:"Youthforia Story Arc — Brand Journey Carousel",potential:88,difficulty:2,tags:["conversion","story","founder"],platforms:["TikTok Spark Ad"],duration:"6 slides",
    hook:"Early days photo + 'From bedroom brand to...'",
    hookNote:"BASED ON: Youthforia's Shark Tank carousel — 6.6M views. Story arc format with founder narrative. 11% higher reach than their video posts. People connect with brand stories. Your journey from startup to 77K followers = compelling story.",
    textOverlay:"Slide 1: 'Started in a bedroom' — Slide 2: 'First order: 1 hoodie' — Slide 3: '77,600 followers later...' — Slide 4: 'Now: premium streetwear, worldwide shipping' — Slide 5: 'The hoodie that started it all — €46.95' — Slide 6: 'Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Youthforia's story arc carousel hit 6.6M views — 11% more reach than their videos. Brand journey content creates emotional connection. Your story from bedroom to 77K followers IS the content. People buy from brands they feel connected to.",
    psychology:"Narrative arc = emotional investment. The viewer roots for you. By the time they see the product, they WANT you to succeed = they want to buy. Founder story = highest trust format after UGC reviews.",
    proof:[{brand:"Youthforia",detail:"Story arc carousel = 6.6M views. 11% higher reach than video. Shark Tank narrative format."},{brand:"Founder-led content",detail:"Odd Muse: £5M/year from founder content. PacSun: authentic stories drive purchases."}],
    equipment:["Early brand photos (first product, first order, early days)","Current brand photos (products, warehouse, team)","Growth milestone screenshots","Product hero shot"],
    caption:"from day 1",
    audio:"Inspiring/emotional trending sound",
    firstSlide:"Early days photo — bedroom setup, first product prototype. Text: 'Started in a bedroom'",
    backedBy:"Youthforia (6.6M views story carousel), founder-led content psychology",
    sourceLinks:[{label:"Youthforia Carousel Case Study",url:"https://www.modernretail.co/technology/tiktok-is-pushing-brands-to-post-photos-instead-of-videos/"}],
    goal:"CONVERSION via emotional brand connection. Story → trust → purchase.",
    imageRules:"Chronological visual journey. Slide 1 = raw, humble beginning. Each slide shows growth. Final slides = where you are now (premium). The contrast between start and now = the story.",
    products:["Heavyweight Zipped Hoodie (€46.95) — 'the one that started it all'"],
    steps:[
      {title:"Slide 1: The Beginning",action:"Earliest brand photo. First product, bedroom workspace, humble start. Text: 'Started in a bedroom'. Raw, unperfect.",camera:"Archive photo",angle:"Whatever you have from early days",lighting:"Doesn't matter — early days should look rough",duration:"",tip:"The more humble the beginning looks, the more impressive the journey. Don't fake it."},
      {title:"Slide 2: First Milestone",action:"First order, first customer, first package shipped. Text: 'First order: 1 hoodie'. The humble start.",camera:"Archive photo",angle:"First product shipped",lighting:"Whatever was available",duration:"",tip:"Real photos from your actual journey. Authenticity is everything here."},
      {title:"Slide 3: Growth",action:"Screenshot of follower growth, or collage of growth moments. Text: '77,600 followers later...' The numbers tell the story.",camera:"Screenshot or collage",angle:"N/A",lighting:"N/A",duration:"",tip:"77,600 followers from a bedroom = impressive. Let the numbers speak."},
      {title:"Slide 4: Now",action:"Current brand: products, warehouse, premium packaging. Text: 'Now: premium streetwear, worldwide shipping'. Show how far you've come.",camera:"Current brand photos",angle:"Professional, premium feel",lighting:"Good, modern",duration:"",tip:"The contrast between slide 1 and slide 4 IS the story. Bedroom → brand."},
      {title:"Slide 5: The Product — Full Circle",action:"Hero shot of Heavyweight Zipped Hoodie. Text: 'The hoodie that started it all — €46.95'. Connect the story back to the product.",camera:"Best product photo",angle:"Hero shot, premium",lighting:"Best possible",duration:"",tip:"The product is the hero of the story. Everything led to this."},
      {title:"Slide 6: CTA",action:"Logo + 'Shop Now ⬇️ — Be part of the story'. Invites the viewer to join.",camera:"Canva design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"'Be part of the story' = they're not just buying a hoodie, they're supporting a brand journey."}
    ]
  },
  {
    id:"s10",title:"Hidden Discount on Final Slide — Swipe Bait",potential:90,difficulty:1,tags:["conversion","FOMO","discount"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Product showcase + 'Swipe to the end for something special'",
    hookNote:"BASED ON: Shopify's documented carousel tactic — hidden discount code on final slide, limited to first 15 users. Forces complete swipe-through (= algorithm boost) + creates urgency (limited codes). Each swipe = engagement signal for Spark Ad performance.",
    textOverlay:"Slide 1: 'Our bestsellers 🔥 (swipe to the end)' — Slide 2: 'Distorted Knit — €41.95' — Slide 3: 'Heavyweight Zipped Hoodie — €46.95' — Slide 4: 'Denim Striped Barrel Jeans — €34.95' — Slide 5: '🎁 Use code TIKTOK15 for 15% off — first 50 only'",
    cta:"Shop Now + discount code via Spark Ad",
    why:"Shopify documented this as a high-conversion carousel tactic. The hidden discount forces 100% swipe-through (every slide viewed = algorithm boost). Limited quantity ('first 50 only') creates urgency. Your top 3 bestsellers as the content = product showcase + conversion.",
    psychology:"Curiosity ('swipe to the end') forces engagement. Sunk cost: after swiping through 4 slides, not buying feels like wasting the effort. Exclusive discount = reward for engagement. Limited quantity = buy NOW.",
    proof:[{brand:"Shopify carousel tactic",detail:"12-slide carousel with hidden discount on final slide. Documented conversion tactic."},{brand:"FOMO + exclusive discount",detail:"Limited codes create urgency. Exclusivity = higher conversion than open discounts."}],
    equipment:["Product photos of top 3 bestsellers","Detail shots","Discount code graphic for final slide"],
    caption:"swipe to the end 👀",
    audio:"Build-up trending sound",
    firstSlide:"Grid of 3 bestselling products. Text: 'Our bestsellers 🔥 (swipe to the end)'",
    backedBy:"Shopify hidden discount tactic, FOMO psychology, swipe-through = algorithm boost",
    sourceLinks:[{label:"Shopify Carousel Tactic",url:"https://www.shopify.com/blog/how-to-make-a-slideshow-on-tiktok"},{label:"Carousel Conversion Guide",url:"https://getkoro.app/blog/tiktok-slideshow"}],
    goal:"CONVERSION via hidden discount + forced swipe-through. Algorithm boost + urgency = sales.",
    imageRules:"Each slide = 1 bestselling product with price. Final slide = exclusive discount code + limited quantity urgency. Clean, consistent product photography throughout.",
    products:["'Distorted' Knit (€41.95) — #1 Bestseller","Heavyweight Zipped Hoodie (€46.95) — #2 Bestseller","Denim Striped Barrel Jeans (€34.95) — #3 Bestseller"],
    steps:[
      {title:"Slide 1: Hook — Bestsellers + Swipe Bait",action:"Grid of your top 3 products. Text: 'Our bestsellers 🔥 (swipe to the end)'. The 'swipe to the end' creates curiosity — what's at the end?",camera:"Product grid or collage",angle:"All 3 products visible",lighting:"Clean, even",duration:"5 min",tip:"The 'swipe to the end' hook forces complete engagement. Every swipe = algorithm fuel."},
      {title:"Slide 2: Bestseller #1 — Distorted Knit",action:"'Distorted' Knit — clean product shot or on-body. Text: '#1 Bestseller — Distorted Knit — €41.95'. Your top seller gets the spotlight.",camera:"Phone — product or on-body",angle:"Show unique pattern",lighting:"Good",duration:"",tip:"Your #1 bestseller for a reason. Let it shine."},
      {title:"Slide 3: Bestseller #2 — Heavyweight Hoodie",action:"Heavyweight Zipped Hoodie. Text: '#2 — Heavyweight Zipped Hoodie — €46.95 — 7 colors'. Second product + price.",camera:"Phone",angle:"Product or on-body",lighting:"Good",duration:"",tip:"7 colorways = mention it. Choice = higher purchase consideration."},
      {title:"Slide 4: Bestseller #3 — Barrel Jeans",action:"Denim Striped Barrel Jeans. Text: '#3 — Denim Striped Barrel Jeans — €34.95'. Third product at impulse price.",camera:"Phone",angle:"Show the striped barrel shape",lighting:"Good",duration:"",tip:"€34.95 = lowest price of the three. Good anchor for the discount on next slide."},
      {title:"Slide 5: THE REWARD — Discount Code",action:"Bold graphic: '🎁 Use code TIKTOK15 for 15% off — first 50 only'. This is the payoff for swiping all the way. Limited = urgency.",camera:"Canva design — bold, eye-catching",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"'First 50 only' creates real urgency. Track the code to measure conversion directly."}
    ]
  },
  {
    id:"s11",title:"\"Fashion Killa\" Outfit Reveal Trend",potential:89,difficulty:1,tags:["conversion","trend","outfit-reveal"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Selfie/pose + 'Don't make me mad or I'll throw a fit'",
    hookNote:"BASED ON: 'Fashion Killa' TikTok carousel trend — hundreds of millions of views. Format: slide 1 = caption setup ('throw a fit'), remaining slides = outfit reveals. Pun on 'fit' (outfit) = humor + product showcase. Trending audio = algorithm boost.",
    textOverlay:"Slide 1: 'Don't make me mad or I'll throw a fit 😤' — Slide 2: (outfit 1 — no text) — Slide 3: (outfit 2 — no text) — Slide 4: (outfit 3 — no text) — Slide 5: 'All pieces: NEWGARMENTS — Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"The 'Fashion Killa' carousel trend has hundreds of millions of views. The pun ('throw a fit' = have a tantrum / show an outfit) is instantly engaging. Trending format = algorithm boost. Product showcase disguised as a meme = zero ad resistance.",
    psychology:"Humor = ad resistance down. The pun is universally understood on FashionTok. Each outfit reveal = product showcase without feeling like a showcase. Multiple outfits = versatility proof. Trending format = discoverability.",
    proof:[{brand:"Fashion Killa trend",detail:"Hundreds of millions of views across TikTok. #1 fashion carousel trend."},{brand:"Meme format",detail:"Humor-based carousels = highest share rate. Shared for the joke, sells through the fit."}],
    equipment:["3 complete outfits using NEWGARMENTS products","Confident selfie/pose for slide 1","Full outfit photos for reveals"],
    caption:"try me 😤",
    audio:"'Fashion Killa' trending audio",
    firstSlide:"Confident selfie/pose. Text: 'Don't make me mad or I'll throw a fit 😤'",
    backedBy:"Fashion Killa carousel trend (hundreds of millions of views), trending audio algorithm boost",
    sourceLinks:[{label:"Fashion Killa Trend Examples",url:"https://www.tiktok.com/discover/fashion-killa-throw-a-fit"},{label:"Fashion Killa Carousel Format",url:"https://www.tiktok.com/discover/dont-make-me-mad-or-ill-throw-a-fit"}],
    goal:"CONVERSION via trending meme format. Product showcase disguised as humor.",
    imageRules:"Slide 1 = attitude/confident selfie (no product focus). Slides 2-4 = full outfit reveals wearing NEWGARMENTS. Slide 5 = product list + CTA. Each outfit must be fire.",
    products:["Zip Hoodie Y2K — Dark Green (€42.95)","Retro Patchwork Barrel Jeans — Blue (€37.95)","Heavyweight Zipped Hoodie — Black (€46.95)","Checkered Inside Out Zipper — Gray (€43.95)"],
    steps:[
      {title:"Slide 1: The Setup — 'Throw a Fit'",action:"Confident selfie or attitude pose. No NEWGARMENTS product visible yet. Text: 'Don't make me mad or I'll throw a fit 😤'. The pun IS the hook.",camera:"Phone — selfie",angle:"Face/upper body, confident expression",lighting:"Good",duration:"",tip:"The attitude is key. Look like you're about to do something. The 'fit' reveal is the payoff."},
      {title:"Slide 2: Fit #1 — Y2K Vibe",action:"Full outfit: Zip Hoodie Y2K (Dark Green) + Retro Patchwork Barrel Jeans (Blue). No text. Let the fit speak.",camera:"Phone — full body",angle:"Full outfit visible",lighting:"Natural",duration:"",tip:"This is the first 'fit' — it needs to slap. Y2K + patchwork = trendy combo."},
      {title:"Slide 3: Fit #2 — Classic Streetwear",action:"Full outfit: Heavyweight Zipped Hoodie (Black) + Denim Striped Barrel Jeans (Blue). No text. Different vibe than fit 1.",camera:"Phone — full body",angle:"Full outfit, different pose",lighting:"Natural",duration:"",tip:"Completely different vibe than slide 2. Versatility across fits = more products showcased."},
      {title:"Slide 4: Fit #3 — Statement Piece",action:"Full outfit: Checkered Inside Out Zipper (Gray) + Oversized Washed Blue Jeans. No text. The boldest fit.",camera:"Phone — full body",angle:"Full outfit, confident pose",lighting:"Natural",duration:"",tip:"End on the boldest, most eye-catching outfit. This is the 'save' slide."},
      {title:"Slide 5: Product List + CTA",action:"List all products with prices. Text: 'All pieces: NEWGARMENTS — Shop Now ⬇️'. Price each item. Total the outfit.",camera:"Canva graphic",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"Listing each product + price = shopping list. Viewers screenshot this slide."}
    ]
  },
  {
    id:"s12",title:"Y2K Stars Knit — \"The Knit That Broke TikTok\"",potential:87,difficulty:1,tags:["conversion","hype","single-product"],platforms:["TikTok Spark Ad"],duration:"4 slides",
    hook:"Close-up of Y2K Stars pattern + 'The knit that keeps selling out'",
    hookNote:"BASED ON: SKIMS single-product viral strategy — 100M+ views, 250K units sold, 46K waitlist on ONE product. Focus ALL attention on ONE standout product with a unique visual hook. Your Y2K Stars Knitted Sweater has a visually striking star pattern = perfect for this.",
    textOverlay:"Slide 1: 'The knit everyone's been asking about' — Slide 2: (on-body shot — no text) — Slide 3: 'Y2K Stars Knitted Sweater — €45.95' — Slide 4: 'Limited stock — Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"SKIMS proved that focusing ALL marketing energy on ONE standout product = maximum virality. Their slip dress hit 100M+ views and sold 250K units. Your Y2K Stars Knit has the visual distinctiveness to be YOUR 'one product' viral moment.",
    psychology:"Single product focus = no choice paralysis. The unique star pattern = visually memorable. 'Everyone's been asking' = social proof. Limited stock = scarcity/FOMO. SKIMS created a 46K waitlist with this exact approach.",
    proof:[{brand:"SKIMS",detail:"100M+ views on ONE product. 250K units sold. 46K waitlist. Single-product focus strategy."},{brand:"Viral product strategy",detail:"One hero product becomes brand identity. All attention on one item = maximum conversion."}],
    equipment:["Y2K Stars Knitted Sweater — close-up of star pattern","On-body lifestyle shots","Product flat lay","Logo + scarcity CTA"],
    caption:"that one 🌟",
    audio:"Hype trending sound",
    firstSlide:"Macro close-up of the Y2K stars pattern. Text: 'The knit everyone's been asking about'",
    backedBy:"SKIMS single-product viral strategy (100M+ views, 250K units, 46K waitlist)",
    sourceLinks:[{label:"SKIMS Viral Product Strategy",url:"https://www.newdaystudio.co/blog/tiktok-brands-that-went-viral"}],
    goal:"CONVERSION via single-product viral focus. All attention on ONE standout item.",
    imageRules:"Every slide = the Y2K Stars Knitted Sweater from a different angle/context. The star pattern must be clearly visible in every shot. No other products — ONLY this one.",
    products:["Y2K Stars Knitted Sweater — White (€45.95)"],
    steps:[
      {title:"Slide 1: Pattern Close-Up — The Visual Hook",action:"Macro close-up of the Y2K star pattern on the sweater. The pattern is visually unique and eye-catching. Text: 'The knit everyone's been asking about'. The pattern stops the scroll.",camera:"Phone — macro",angle:"Close-up of star pattern detail",lighting:"Good light to show pattern clearly",duration:"",tip:"The star pattern IS the hook. Make it big, clear, detailed. SKIMS used the product's unique look as the entire marketing strategy."},
      {title:"Slide 2: On-Body — The Look",action:"Person wearing the Y2K Stars Knitted Sweater, styled. Full outfit. No text — let the look speak. The sweater is the star.",camera:"Phone — friend-shot or mirror",angle:"Full outfit, sweater clearly visible",lighting:"Natural, good",duration:"",tip:"Style it well. The on-body shot is where the viewer imagines wearing it."},
      {title:"Slide 3: Product + Price",action:"Clean product shot. Text: 'Y2K Stars Knitted Sweater — €45.95'. Name + price, clear and direct.",camera:"Phone — flat lay or hanger",angle:"Full product visible",lighting:"Clean",duration:"",tip:"After the visual hook + on-body, the price is the only thing standing between desire and purchase."},
      {title:"Slide 4: Scarcity + CTA",action:"Text: 'Limited stock — Shop Now ⬇️'. Scarcity trigger + direct CTA. SKIMS created a 46K waitlist with this approach.",camera:"Canva design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"'Limited stock' = real urgency. If you can track actual stock levels, mention the number."}
    ]
  },
  {
    id:"s13",title:"BUY 2 GET 30% OFF — Bundle Deal Showcase",potential:94,difficulty:1,tags:["conversion","bundle","discount"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Stack of products + 'The deal nobody's talking about'",
    hookNote:"BASED ON: Your existing BUY 2 GET 30% OFF / BUY 3 GET 40% OFF promotion. COMFRT's live-shopping format uses limited-time discounts as the primary conversion driver. Combine your existing deal with visual product stacking for maximum AOV.",
    textOverlay:"Slide 1: 'The deal nobody's talking about 👀' — Slide 2: 'BUY 2 → 30% OFF' — Slide 3: 'BUY 3 → 40% OFF' — Slide 4: 'BUY 4 → 40% OFF + FREE GIFT 🎁' — Slide 5: 'Shop Now — deals end when stock runs out'",
    cta:"Shop Now via Spark Ad",
    why:"Your existing tiered discount (30%/40%/40%+gift) is a strong conversion driver but needs visual presentation. COMFRT drives millions through limited-time discounts during live streams. A carousel showcasing the escalating deal creates urgency at each tier.",
    psychology:"Escalating discounts: each tier is MORE generous = the viewer wants the BEST deal. 'BUY 4 + FREE GIFT' feels like the ultimate win. Loss aversion: not getting the better discount = leaving money on table. Higher AOV = more revenue per customer.",
    proof:[{brand:"COMFRT",detail:"$23.31M using limited-time discounts as primary conversion driver."},{brand:"Tiered discounts",detail:"Escalating discount tiers increase AOV by 35-50% vs single discount."}],
    equipment:["Photos of 2, 3, 4 products stacked/grouped","Price calculation graphics for each tier","Product photos of bestsellers","Logo + urgency CTA"],
    caption:"you're welcome 🤝",
    audio:"Upbeat trending sound",
    firstSlide:"Stack of NEWGARMENTS products (hoodie, knit, jeans). Text: 'The deal nobody's talking about 👀'",
    backedBy:"COMFRT discount model ($23.31M), tiered discount psychology (35-50% AOV increase)",
    sourceLinks:[{label:"COMFRT Sales Model",url:"https://www.tiktok.com/@comfrt"},{label:"Tiered Discount Strategy",url:"https://newgarments.store/nl/collections/warehouse-sale"}],
    goal:"CONVERSION + maximum AOV. Escalating discounts drive multi-item orders.",
    imageRules:"Each slide = more products stacked. Visual escalation from 2 → 3 → 4 items. Price calculations visible. The FREE GIFT on tier 4 = the cherry on top.",
    products:["'Distorted' Knit (€41.95)","Heavyweight Zipped Hoodie (€46.95)","Denim Striped Barrel Jeans (€34.95)","Retro Patchwork Barrel Jeans (€37.95)"],
    steps:[
      {title:"Slide 1: Hook — The Deal",action:"Stack/pile of NEWGARMENTS products. Text: 'The deal nobody's talking about 👀'. Create curiosity about what the deal is.",camera:"Phone — pile of products",angle:"Above or 3/4 showing multiple items",lighting:"Clean",duration:"",tip:"The hook implies an INSIDER deal. Curiosity + deal = irresistible swipe."},
      {title:"Slide 2: Tier 1 — BUY 2 GET 30% OFF",action:"2 products together (e.g., Distorted Knit + Heavyweight Hoodie). Text: 'BUY 2 → 30% OFF' + original price → discounted price. Math visible.",camera:"Phone — 2 products",angle:"Both products visible",lighting:"Clean",duration:"",tip:"Show the actual math: €41.95 + €46.95 = €88.90 → 30% OFF = €62.23. The saving is real."},
      {title:"Slide 3: Tier 2 — BUY 3 GET 40% OFF",action:"3 products together. Text: 'BUY 3 → 40% OFF'. Even bigger discount = even more value.",camera:"Phone — 3 products",angle:"All 3 visible",lighting:"Clean",duration:"",tip:"The escalation from 30% to 40% makes the viewer think: 'if I'm buying 2, I might as well get 3.'"},
      {title:"Slide 4: Tier 3 — THE ULTIMATE DEAL",action:"4 products + FREE GIFT visual. Text: 'BUY 4 → 40% OFF + FREE GIFT 🎁'. The best deal of all. This is the 'I need this' slide.",camera:"Phone or Canva — 4 products + gift icon",angle:"All products + gift visual",lighting:"Clean, celebratory",duration:"",tip:"The FREE GIFT is the cherry on top. After seeing 30% → 40% → 40%+gift, tier 3 is the obvious choice."},
      {title:"Slide 5: CTA — Urgency Close",action:"Logo + 'Shop Now — deals end when stock runs out ⬇️'. The urgency is real: your site says 'WEBSITE WILL BE CLOSED ONCE SOLD OUT'.",camera:"Canva design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"The urgency ties to your actual business model (limited stock). It's real, not manufactured."}
    ]
  },
  {
    id:"s14",title:"\"Structure\" Knit Texture Showcase — ASMR Style",potential:85,difficulty:1,tags:["conversion","texture","aesthetic"],platforms:["TikTok Spark Ad"],duration:"4 slides",
    hook:"Extreme close-up of knit texture + 'Feel this through your screen'",
    hookNote:"BASED ON: Product texture/ASMR carousel trend on FashionTok. Close-up fabric shots with 'satisfying' texture = high save rate + purchase curiosity. Your 'Structure' Graphic Knitted Sweater has a tactile, 3D texture that photographs incredibly well.",
    textOverlay:"Slide 1: 'Feel this through your screen' — Slide 2: 'Structure Graphic Knitted Sweater' — Slide 3: 'Heavyweight knit — €46.95' — Slide 4: '2 colors available — Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Texture/ASMR content is huge on TikTok. Close-up fabric shots trigger a 'I need to feel this' response. Your 'Structure' knit has a 3D graphic pattern that is uniquely photogenic. This format turns fabric texture into desire.",
    psychology:"Tactile curiosity: when people SEE interesting texture, they WANT to feel it. The only way to feel it = buy it. Close-up macro photography makes the texture feel 3D. Saves = 'I want to come back to this' = algorithm boost.",
    proof:[{brand:"Texture/ASMR TikTok",detail:"Fabric texture close-ups = high save rate. 'I need to feel this' response."},{brand:"Product photography",detail:"TikTok data: showing product in use = +175% conversion. Close-ups of construction = trust."}],
    equipment:["'Structure' Graphic Knitted Sweater — macro close-ups","On-body styled shots","Both colorways (Black + Moss Green)","Logo + CTA"],
    caption:"trust the texture",
    audio:"Soft/satisfying ASMR trending sound",
    firstSlide:"Extreme macro close-up of the 3D graphic knit pattern. Text: 'Feel this through your screen'",
    backedBy:"Texture/ASMR content trend, tactile curiosity psychology, product close-up = +175% conversion",
    sourceLinks:[{label:"Texture Showcase Fashion TikTok",url:"https://www.tiktok.com/discover/satisfying-fabric-texture"},{label:"Product Photography Impact",url:"https://nightjar.so/blog/product-photography-for-tiktok-shop-what-sells-vs-what-scrolls"}],
    goal:"CONVERSION via tactile curiosity. 'I need to FEEL this' → buy.",
    imageRules:"Slide 1 = EXTREME close-up (macro). Show every fiber, every knit pattern detail. Must look 3D and tactile. Slides 2-3 = progressively zoom out to show full product. Slide 4 = CTA.",
    products:["'Structure' Graphic Knitted Sweater — Black (€46.95)","'Structure' Graphic Knitted Sweater — Moss Green (€46.95)"],
    steps:[
      {title:"Slide 1: Macro Texture — The Hook",action:"EXTREME close-up of the 'Structure' knit pattern. Fill the entire frame with texture. Text: 'Feel this through your screen'. The texture is the hook.",camera:"Phone — macro mode, as close as possible",angle:"Directly on fabric surface",lighting:"Angled light to show 3D texture and shadows",duration:"",tip:"Use angled lighting to create shadows in the knit pattern. This makes the texture look 3D and touchable."},
      {title:"Slide 2: Product Reveal",action:"Zoom out to show the full sweater. Text: 'Structure Graphic Knitted Sweater'. Now the viewer sees the complete product.",camera:"Phone — product shot",angle:"Full product visible",lighting:"Good",duration:"",tip:"The transition from macro to full product = satisfying reveal."},
      {title:"Slide 3: On-Body + Price",action:"Person wearing it, styled. Text: 'Heavyweight knit — €46.95'. Show how it looks IRL.",camera:"Phone — friend-shot",angle:"Full outfit",lighting:"Natural",duration:"",tip:"After the texture hook, seeing it on a real person completes the picture."},
      {title:"Slide 4: Both Colors + CTA",action:"Both colorways (Black + Moss Green) side by side. Text: '2 colors available — Shop Now ⬇️'.",camera:"Product photo or flat lay",angle:"Both colors visible",lighting:"Clean",duration:"",tip:"2 colors = choice without overwhelm. CTA after texture + on-body = ready to buy."}
    ]
  },
  {
    id:"s15",title:"\"10 Comments Get a Surprise\" Engagement Bait + Showcase",potential:93,difficulty:1,tags:["conversion","engagement","own-proven"],platforms:["TikTok Spark Ad"],duration:"5 slides",
    hook:"Product collage + 'The first 10 comments get a surprise :)'",
    hookNote:"BASED ON: Your own #3 post — 668,600 views, 1,486 likes. Caption: 'The first 10 comments will get a surprise :)'. This drove 11 comments (high for your account) and massive views. The engagement bait + product showcase = Spark Ad algorithm fuel. Every comment = more reach.",
    textOverlay:"Slide 1: 'New drops just landed 🔥' — Slide 2: 'Heavyweight Zipped Hoodie — 7 colors — €46.95' — Slide 3: 'Distorted Knit — €41.95' — Slide 4: 'Denim Striped Barrel Jeans — €34.95' — Slide 5: 'BUY 2 GET 30% OFF — Shop Now ⬇️'",
    cta:"Shop Now via Spark Ad",
    why:"Your 'first 10 comments' caption got 668K views on its FIRST use. Comments = direct algorithm fuel for Spark Ads. More comments = more reach = more conversions. Combined with product showcase of your top 3 bestsellers + your existing discount deal.",
    psychology:"Engagement bait: 'surprise' creates curiosity + motivation to comment. Every comment = Spark Ad algorithm signal. The product showcase ensures the engagement is paired with purchase opportunity. Comments from viewers attract more viewers (social proof).",
    proof:[{brand:"NEWGARMENTS own post #3",detail:"668,600 views with 'first 10 comments get a surprise' caption. Your 3rd best post."},{brand:"Comment algorithm",detail:"Every comment = engagement signal. For Spark Ads, comments directly improve ad performance and reach."}],
    equipment:["Product photos of top 3 bestsellers","On-body shots","Discount deal graphic","Logo + CTA"],
    caption:"the first 10 comments get a surprise :)",
    audio:"Upbeat trending sound",
    firstSlide:"Product collage of top 3 bestsellers. Text: 'New drops just landed 🔥'",
    backedBy:"Your own #3 post (668K views), comment algorithm = Spark Ad fuel",
    sourceLinks:[{label:"YOUR #3 POST (668K views)",url:"https://www.tiktok.com/@newgarmentsclo"}],
    goal:"ENGAGEMENT + CONVERSION. Comments fuel Spark Ad reach, product showcase drives purchases.",
    imageRules:"Clean product showcase format. Each bestseller gets its own slide with price. Final slide = discount deal + CTA. Professional-looking but not overly polished.",
    products:["Heavyweight Zipped Hoodie (€46.95)","'Distorted' Knit (€41.95)","Denim Striped Barrel Jeans (€34.95)"],
    steps:[
      {title:"Slide 1: Hook — New Drops",action:"Collage or grid of your top 3 products. Text: 'New drops just landed 🔥'. Visual impact of multiple products.",camera:"Product photos in grid",angle:"Clean product shots",lighting:"Good, consistent",duration:"5 min",tip:"The caption 'first 10 comments get a surprise' drove 668K views for you. Use it again."},
      {title:"Slide 2: Bestseller #1 — Hoodie",action:"Heavyweight Zipped Hoodie — show all 7 colorways or best color on-body. Text: 'Heavyweight Zipped Hoodie — 7 colors — €46.95'.",camera:"Phone",angle:"On-body or flat lay",lighting:"Good",duration:"",tip:"Your #2 bestseller with 7 color options = high chance someone finds their color."},
      {title:"Slide 3: Bestseller #2 — Knit",action:"'Distorted' Knit on-body or product shot. Text: 'Distorted Knit — €41.95'. Your #1 bestseller.",camera:"Phone",angle:"Showing unique distorted pattern",lighting:"Good",duration:"",tip:"#1 bestseller. The unique pattern is the visual hook."},
      {title:"Slide 4: Bestseller #3 — Jeans",action:"Denim Striped Barrel Jeans. Text: 'Denim Striped Barrel Jeans — €34.95'. Impulse price point.",camera:"Phone",angle:"Show barrel shape + stripes",lighting:"Good",duration:"",tip:"€34.95 = impulse buy territory. Lowest price of the three = easy first purchase."},
      {title:"Slide 5: Deal + CTA",action:"Text: 'BUY 2 GET 30% OFF — Shop Now ⬇️'. The discount after seeing 3 products = 'which 2 should I get?'.",camera:"Canva design",angle:"N/A",lighting:"N/A",duration:"5 min",tip:"After 3 products, the viewer is thinking 'which one?'. The BUY 2 discount answers: 'get two.'"}
    ]
  }
];
